import { FoodItem } from './data';

export const FOOD_DATABASE_ITEMS: FoodItem[] = [
  {
    id: "ragi_mudde",
    name: {
      en: "Ragi Mudde (Finger Millet Ball)",
      kn: "ರಾಗಿ ಮುದ್ದೆ",
      hi: "रागी मुद्दे (रागी के लड्डू)",
      ta: "கேழ்வரகு களி (ராகி களி)",
      te: "రాగి ముద్ద"
    },
    category: "Millets",
    calories: 320,
    protein: 7.3,
    carbohydrates: 72,
    fat: 1.3,
    fiber: 11.5,
    iron: 3.9,
    calcium: 344,
    folate: 18,
    vitaminA: 6,
    vitaminB6: 0.15,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.85,
    vitaminK: 0.9,
    magnesium: 137,
    potassium: 408,
    zinc: 2.3,
    sodium: 11,
    sugar: 0.6,
    servingSize: "1 medium ball (150g)",
    recommendedQuantity: "1 ball per day",
    safetyLevel: "Safe",
    explanation: {
      en: "Ragi Mudde is a powerhouse of calcium and dietary fiber. It helps prevent gestational diabetes and supports bone development in the baby.",
      kn: "ರಾಗಿ ಮುದ್ದೆಯು ಕ್ಯಾಲ್ಸಿಯಂ ಮತ್ತು ನಾರಿನಂಶದ ಗಣಿಯಾಗಿದೆ. ಇದು ಗರ್ಭಾವಸ್ಥೆಯ ಮಧುಮೇಹವನ್ನು ತಡೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ ಮತ್ತು ಮಗುವಿನ ಮೂಳೆಗಳ ಬೆಳವಣಿಗೆಗೆ ಪೂರಕವಾಗಿದೆ.",
      hi: "रागी मुद्दे कैल्शियम और फाइबर से भरपूर है। यह गर्भकालीन मधुमेह को रोकने और शिशु की हड्डियों के विकास में मदद करता है।",
      ta: "கேழ்வரகு களி கால்சியம் மற்றும் நார்ச்சத்து நிறைந்தது. இது கர்ப்பகால நீரிழிவு நோயைத் தடுக்கவும் குழந்தையின் எலும்பு வளர்ச்சிக்கும் உதவுகிறது.",
      te: "రాగి ముద్ద కాల్షియం మరియు ఫైబర్ సమృద్ధిగా అందిస్తుంది. ఇది గర్భధారణ మధుమేహాన్ని నిరోధించి, శిశువు ఎముకల ఎదుగుదలకు తోడ్పడుతుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Outstanding source of calcium for fetal skeletal development; high fiber helps manage digestive health and blood sugar levels.",
      kn: "ಮಗುವಿನ ಅಸ್ಥಿಪಂಜರದ ಬೆಳವಣಿಗೆಗೆ ಅತ್ಯುತ್ತಮ ಕ್ಯಾಲ್ಸಿಯಂ ಮೂಲ; ಹೆಚ್ಚಿನ ನಾರಿನಂಶವು ರಕ್ತದ ಸಕ್ಕರೆ ನಿಯಂತ್ರಣಕ್ಕೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
      hi: "भ्रूण के कंकाल विकास के लिए कैल्शियम का उत्कृष्ट स्रोत; उच्च फाइबर पाचन और रक्त शर्करा को नियंत्रित करता है।",
      ta: "குழந்தையின் எலும்பு வளர்ச்சிக்கு சிறந்த கால்சியம் ஆதாரம்; நார்ச்சத்து இரத்த சர்க்கரையை கட்டுக்குள் வைக்கிறது.",
      te: "పిండం అస్థిపంజర అభివృద్ధికి కాల్షియం యొక్క అద్భుతమైన వనరు; అధిక ఫైబర్ జీర్ణక్రియను మెరుగుపరుస్తుంది."
    },
    risks: {
      en: "Ensure it is consumed hot and with clean accompaniments like mild sambar. Avoid heavy/spicy curries if suffering from acid reflux.",
      kn: "ಇದನ್ನು ಬಿಸಿಯಾಗಿರುವಾಗ ಮತ್ತು ಮಿತವಾದ ಸಾರಿನೊಂದಿಗೆ ಸೇವಿಸಿ. ಆಸಿಡ್ ರಿಫ್ಲಕ್ಸ್ ಇದ್ದರೆ ಮಸಾಲೆಯುಕ್ತ ಸಾರನ್ನು ತಪ್ಪಿಸಿ.",
      hi: "इसे गर्म-गर्म खाएं। एसिडिटी की समस्या होने पर अत्यधिक तीखी कढ़ी या सांभर से बचें।",
      ta: "இதனை சூடாகவும் மிதமான சாம்பாருடனும் உட்கொள்ளவும். நெஞ்செரிச்சல் இருந்தால் காரமான குழம்பை தவிர்க்கவும்.",
      te: "దీనిని వేడిగా తినాలి. ఎసిడిటీ ఉన్నప్పుడు కారంగా ఉండే కూరలు వాడకూడదు."
    },
    alternatives: "Jonna Roti, Wheat Chapati, Brown Rice",
    states: ["Karnataka"],
    isVegetarian: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Ragi_Mudde_and_soppusaaru.jpg/800px-Ragi_Mudde_and_soppusaaru.jpg"
  },
  {
    id: "akki_roti",
    name: {
      en: "Akki Roti (Rice Flatbread with Grated Veg)",
      kn: "ಅಕ್ಕಿ ರೊಟ್ಟಿ",
      hi: "अक्की रोटी",
      ta: "அக்கி ரொட்டி",
      te: "అక్కి రొట్టె"
    },
    category: "Breakfast",
    calories: 240,
    protein: 4.2,
    carbohydrates: 48,
    fat: 3.5,
    fiber: 2.8,
    iron: 1.1,
    calcium: 22,
    folate: 12,
    vitaminA: 20,
    vitaminB6: 0.08,
    vitaminB12: 0,
    vitaminC: 2.0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 1.5,
    magnesium: 30,
    potassium: 110,
    zinc: 0.8,
    sodium: 150,
    sugar: 0.4,
    servingSize: "1 medium roti (100g)",
    recommendedQuantity: "1-2 rotis for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "Akki Roti made with rice flour and grated carrots or dill leaves is an easily digestible breakfast option that provides steady morning energy.",
      kn: "ಕ್ಯಾರೆಟ್ ಅಥವಾ ಸಬ್ಬಸಿಗೆ ಸೊಪ್ಪಿನೊಂದಿಗೆ ಮಾಡುವ ಅಕ್ಕಿ ರೊಟ್ಟಿಯು ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗುವ ಉಪಾಹಾರವಾಗಿದ್ದು, ಮುಂಜಾನೆಯ ಶಕ್ತಿಯನ್ನು ನೀಡುತ್ತದೆ.",
      hi: "चावल के आटे, कद्दूकस की हुई गाजर और हरी सब्जियों से बनी अक्की रोटी आसानी से पचने वाली है और ऊर्जा प्रदान करती है।",
      ta: "அரிசி மாவு மற்றும் துருவிய காய்கறிகளுடன் செய்யப்படும் அக்கி ரொட்டி எளிதில் செரிமானமாகி காலையில் நல்ல ஆற்றலைத் தரும்.",
      te: "బియ్యప్పిండి మరియు కూరగాయల తురుముతో చేసే అక్కి రొట్టె సులభంగా జీర్ణమై రోజంతా అవసరమైన శక్తిని అందిస్తుంది."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Gentle on the stomach, gluten-free, and customizable with nutritious vegetables like carrots and onions.",
      kn: "ಹೊಟ್ಟೆಗೆ ಹಿತಕರವಾದ ಮತ್ತು ಗ್ಲುಟನ್-ಮುಕ್ತ ಉಪಾಹಾರ; ಕ್ಯಾರೆಟ್‌ನಂತಹ ಪೌಷ್ಟಿಕ ತರಕಾರಿಗಳನ್ನು ಸೇರಿಸಬಹುದು.",
      hi: "पेट के लिए हल्की, ग्लूटेन-मुक्त, और गाजर जैसी पौष्टिक सब्जियों से भरपूर भोजन।",
      ta: "வயிற்றுக்கு இதமானது, குளுட்டன் இல்லாதது, கேரட் போன்ற காய்கறிகளை சேர்த்து சமைக்கலாம்.",
      te: "జీర్ణక్రియకు సులభంగా ఉంటుంది, గ్లూటెన్ రహితమైనది, క్యారెట్ మరియు ఉల్లిపాయలతో పోషకాలను పెంచవచ్చు."
    },
    risks: {
      en: "Avoid adding too much oil or ghee during preparation. Do not serve with very spicy chutneys to prevent heartburn.",
      kn: "ತಯಾರಿಸುವಾಗ ಹೆಚ್ಚು ಎಣ್ಣೆ ಅಥವಾ ತುಪ್ಪ ಬಳಸಬೇಡಿ. ನೆಂಚಿಕೊಳ್ಳಲು ಅತಿ ಖಾರವಾದ ಚಟ್ನಿ ಬಳಸಬೇಡಿ.",
      hi: "बनाते समय अधिक तेल या घी का प्रयोग न करें। सीने में जलन से बचने के लिए कम तीखी चटनी के साथ खाएं।",
      ta: "தயாரிக்கும் போது அதிக எண்ணெய் அல்லது நெய் சேர்ப்பதை தவிர்க்கவும். காரமான சட்னியுடன் சாப்பிட வேண்டாம்.",
      te: "తయారీలో ఎక్కువ నూనె లేదా నెయ్యి వాడకూడదు. గ్యాస్ట్రిక్ సమస్యలు రాకుండా కారం తక్కువగా ఉన్న చట్నీ వాడాలి."
    },
    alternatives: "Ragi Roti, Dosa, Idli",
    states: ["Karnataka"],
    isVegetarian: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Akki_rotti_with_chutney.jpg/800px-Akki_rotti_with_chutney.jpg"
  },
  {
    id: "bisi_bele_bath",
    name: {
      en: "Bisi Bele Bath (Lentil Rice with Veg)",
      kn: "ಬಿಸಿ ಬೇಳೆ ಬಾತ್",
      hi: "बिसी बेले भात",
      ta: "பிசி பெலே பாத்",
      te: "బిసి బేలే బాత్"
    },
    category: "Traditional Recipes",
    calories: 280,
    protein: 8.5,
    carbohydrates: 48,
    fat: 6.2,
    fiber: 5.4,
    iron: 2.1,
    calcium: 45,
    folate: 40,
    vitaminA: 150,
    vitaminB6: 0.14,
    vitaminB12: 0,
    vitaminC: 12,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 4.5,
    magnesium: 60,
    potassium: 310,
    zinc: 1.2,
    sodium: 250,
    sugar: 1.5,
    servingSize: "1 plate (200g)",
    recommendedQuantity: "1 serving for lunch",
    safetyLevel: "Safe",
    explanation: {
      en: "A complete one-pot meal rich in protein from Toor dal and essential vitamins from assorted fresh vegetables.",
      kn: "ತೊಗರಿ ಬೇಳೆಯ ಪ್ರೋಟೀನ್ ಮತ್ತು ತಾಜಾ ತರಕಾರಿಗಳ ಜೀವಸತ್ವಗಳುಳ್ಳ ಸಂಪೂರ್ಣ ಪೌಷ್ಟಿಕ ಆಹಾರ ಇದಾಗಿದೆ.",
      hi: "तूर दाल के प्रोटीन और ताजी सब्जियों के विटामिन से भरपूर एक संपूर्ण पौष्टिक भोजन।",
      ta: "துவரம் பருப்பின் புரதமும் காய்கறிகளின் வைட்டமின்களும் நிறைந்த ஒரு முழுமையான சத்தான உணவு.",
      te: "కందిపప్పు ప్రోటీన్లు మరియు కూరగాయల విటమిన్లు కలిగిన ఒక సంపూర్ణమైన సమతుల్య భోజనం."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Combines carbohydrates, proteins, and minerals in a single meal, making it excellent for busy maternal schedules.",
      kn: "ಕಾರ್ಬೋಹೈಡ್ರೇಟ್‌ಗಳು, ಪ್ರೋಟೀನ್‌ಗಳು ಮತ್ತು ಖನಿಜಗಳ ಅದ್ಭುತ ಸಂಯೋಜನೆಯಾಗಿದ್ದು, ಗರ್ಭಿಣಿಯರಿಗೆ ಅತ್ಯುತ್ತಮವಾಗಿದೆ.",
      hi: "एक ही भोजन में कार्बोहाइड्रेट, प्रोटीन और खनिज का बेहतरीन संयोजन, जो गर्भवती महिलाओं के लिए उत्तम है।",
      ta: "கார்போஹைட்ரேட், புரதம் மற்றும் தாதுக்கள் நிறைந்த ஒரு எளிய ஆரோக்கியமான உணவு.",
      te: "పిండిపదార్థాలు, ప్రోటీన్లు మరియు ఖనిజాలు ఒకే భోజనంలో లభించే అద్భుతమైన వంటకం."
    },
    risks: {
      en: "Control the spice level and avoid adding excessive ghee or butter. Use a moderate amount of salt.",
      kn: "ಮಸಾಲೆ ಪ್ರಮಾಣವನ್ನು ಕಡಿಮೆ ಮಾಡಿ ಮತ್ತು ಅತಿಯಾದ ತುಪ್ಪ ಅಥವಾ ಬೆಣ್ಣೆ ಬಳಸಬೇಡಿ. ಉಪ್ಪಿನ ಪ್ರಮಾಣ ನಿಯಂತ್ರಣದಲ್ಲಿರಲಿ.",
      hi: "मसालों का स्तर कम रखें और बहुत अधिक घी या मक्खन न डालें। नमक की मात्रा सीमित रखें।",
      ta: "காரத்தை குறைத்து சமைக்கவும், அதிக நெய் அல்லது வெண்ணெய் சேர்ப்பதை தவிர்க்கவும்.",
      te: "కారం మరియు ఉప్పు తక్కువగా వాడాలి. నెయ్యి పరిమితంగా వేయాలి."
    },
    alternatives: "Khichdi, Pongal, Veg Pulav",
    states: ["Karnataka"],
    isVegetarian: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bisi_Bele_Bath.jpg/800px-Bisi_Bele_Bath.jpg"
  },
  {
    id: "mysore_pak",
    name: {
      en: "Mysore Pak (Traditional Chickpea Sweet)",
      kn: "ಮೈಸೂರು ಪಾಕ್",
      hi: "मैसूर पाक",
      ta: "மைசூர் பாக்",
      te: "మైసூர் పాక్"
    },
    category: "Traditional Recipes",
    calories: 380,
    protein: 4.5,
    carbohydrates: 42,
    fat: 22,
    fiber: 1.2,
    iron: 0.8,
    calcium: 30,
    folate: 8,
    vitaminA: 110,
    vitaminB6: 0.03,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 1.2,
    vitaminK: 1.0,
    magnesium: 22,
    potassium: 95,
    zinc: 0.5,
    sodium: 80,
    sugar: 32,
    servingSize: "1 small piece (30g)",
    recommendedQuantity: "Occasional treat (max 1 piece)",
    safetyLevel: "Safe in Moderation",
    explanation: {
      en: "A rich sweet made of chickpea flour, ghee, and sugar. It should be strictly limited, and completely avoided if diagnosed with gestational diabetes.",
      kn: "ಕಡಲೆ ಹಿಟ್ಟು, ತುಪ್ಪ ಮತ್ತು ಸಕ್ಕರೆಯಿಂದ ತಯಾರಿಸಿದ ಸಿಹಿ ತಿನಿಸು. ಗರ್ಭಾವಸ್ಥೆಯ ಮಧುಮೇಹವಿದ್ದರೆ ಇದನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ತಪ್ಪಿಸಬೇಕು.",
      hi: "बेसन, घी और चीनी से बनी एक पारंपरिक मिठाई। गर्भकालीन मधुमेह होने पर इसका सेवन बिलकुल न करें।",
      ta: "கடலை மாவு, நெய் மற்றும் சர்க்கரையால் செய்யப்படும் இனிப்பு. கர்ப்பகால நீரிழிவு இருந்தால் முற்றிலும் தவிர்க்கவும்.",
      te: "శనగపిండి, నెయ్యి మరియు చక్కెరతో చేసే సాంప్రదాయ మిఠాయి. గర్భధారణ మధుమేహం ఉంటే దీనిని తినకూడదు."
    },
    trimester: "All",
    bestTime: "Evening Snack",
    benefits: {
      en: "Provides quick energy and contains chickpea flour which offers some basic plant protein.",
      kn: "ತ್ವರಿತ ಶಕ್ತಿಯನ್ನು ನೀಡುತ್ತದೆ ಮತ್ತು ಕಡಲೆ ಹಿಟ್ಟಿನಿಂದ ಸ್ವಲ್ಪ ಪ್ರಮಾಣದ ಸಸ್ಯಜನ್ಯ ಪ್ರೋಟೀನ್ ದೊರೆಯುತ್ತದೆ.",
      hi: "त्वरित ऊर्जा प्रदान करता है और बेसन के कारण इसमें कुछ मात्रा में प्रोटीन होता है।",
      ta: "உடனடி ஆற்றலைத் தருகிறது மற்றும் கடலை மாவிலிருந்து சிறிதளவு புரதம் கிடைக்கிறது.",
      te: "శీఘ్ర శక్తిని అందిస్తుంది మరియు శనగపిండి ద్వారా కొద్దిగా ప్రోటీన్ లభిస్తుంది."
    },
    risks: {
      en: "High glycemic index and heavy saturated fats. Contraindicated for gestational diabetes and hypertension.",
      kn: "ಹೆಚ್ಚಿನ ಸಕ್ಕರೆ ಮತ್ತು ಕೊಬ್ಬಿನಂಶ ಇರುವುದರಿಂದ ಮಧುಮೇಹ ಮತ್ತು ರಕ್ತದೊತ್ತಡ ಹೊಂದಿರುವವರಿಗೆ ಹಾನಿಕಾರಕ.",
      hi: "उच्च शर्करा और वसा की मात्रा। गर्भकालीन मधुमेह और उच्च रक्तचाप के रोगियों के लिए अनुशंसित नहीं है।",
      ta: "அதிக சர்க்கரை மற்றும் கொழுப்பு உள்ளது. நீரிழிவு மற்றும் இரத்த அழுத்தம் உள்ளவர்கள் தவிர்க்க வேண்டும்.",
      te: "అధిక చక్కెర మరియు కొవ్వుల శాతం కలిగి ఉంది. మధుమేహం మరియు రక్తపోటు ఉన్నవారికి హానికరం."
    },
    alternatives: "Sesame Chikki, Fresh Palm Fruit, Dates",
    states: ["Karnataka"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "ven_pongal",
    name: {
      en: "Ven Pongal (Savory Moong Dal Rice)",
      kn: "ವೆನ್ ಪೊಂಗಲ್",
      hi: "वेन पोंगल",
      ta: "வெண் பொங்கல்",
      te: "వెన్ పొంగల్"
    },
    category: "Breakfast",
    calories: 210,
    protein: 6.8,
    carbohydrates: 38,
    fat: 4.5,
    fiber: 3.2,
    iron: 1.8,
    calcium: 32,
    folate: 28,
    vitaminA: 60,
    vitaminB6: 0.11,
    vitaminB12: 0,
    vitaminC: 1.5,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 1.1,
    magnesium: 42,
    potassium: 185,
    zinc: 0.8,
    sodium: 190,
    sugar: 0.5,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1 plate for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "A soft, easily chewable blend of rice and yellow moong dal, seasoned with black pepper, ginger, and cumin. Highly comforting for morning sickness.",
      kn: "ಅಕ್ಕಿ ಮತ್ತು ಹೆಸರು ಬೇಳೆಯ ಮೃದುವಾದ ಮಿಶ್ರಣ. ಕಾಳುಮೆಣಸು, ಶುಂಠಿ ಮತ್ತು ಜೀರಿಗೆಯ ಒಗ್ಗರಣೆಯು ವಾಕರಿಕೆ ಮತ್ತು ಮುಂಜಾನೆಯ ಆಯಾಸಕ್ಕೆ ಹಿತಕರ.",
      hi: "चावल और मूंग दाल का एक नरम मिश्रण, जिसे काली मिर्च, अदरक और जीरे से पकाया जाता है। सुबह की उल्टी (Morning Sickness) में बहुत आरामदायक।",
      ta: "அரிசி மற்றும் பாசிப்பருப்பின் மென்மையான கலவை, மிளகு, இஞ்சி மற்றும் சீரகத்துடன் சமைக்கப்படுகிறது. காலையில் ஏற்படும் குமட்டலுக்கு மிகவும் நல்லது.",
      te: "బియ్యం మరియు పెసరపప్పుతో మెత్తగా వండిన వంటకం, మిరియాలు, అల్లం మరియు జీలకర్రతో తాలింపు వేస్తారు. గర్భిణుల వికారానికి మేలు చేస్తుంది."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Yellow moong dal is a highly digestible source of protein and folate. Ginger and cumin aid digestive health and relieve nausea.",
      kn: "ಹೆಸರು ಬೇಳೆಯು ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗುವ ಪ್ರೋಟೀನ್ ಮತ್ತು ಫೋಲೇಟ್ ನೀಡುತ್ತದೆ. ಶುಂಠಿ ಮತ್ತು ಜೀರಿಗೆಯು ಜೀರ್ಣಕ್ರಿಯೆಯನ್ನು ಸುಧಾರಿಸುತ್ತದೆ.",
      hi: "मूंग दाल आसानी से पचने वाला प्रोटीन और फोलेट प्रदान करती है। अदरक और जीरा पाचन में सुधार करते हैं।",
      ta: "பாசிப்பருப்பு எளிதில் செரிமானமாகக்கூடிய புரதம் மற்றும் ஃபோலேட் வழங்குகிறது. இஞ்சியும் சீரகமும் செரிமானத்தை சீராக்கும்.",
      te: "పెసరపప్పు సులభంగా జీర్ణమయ్యే ప్రోటీన్ మరియు ఫోలేట్ అందిస్తుంది. అల్లం, జీలకర్ర వికారాన్ని తగ్గిస్తాయి."
    },
    risks: {
      en: "Limit the amount of whole cashews and ghee added to avoid excess saturated fat intake.",
      kn: "ಹೆಚ್ಚಿನ ಕೊಬ್ಬನ್ನು ತಪ್ಪಿಸಲು ಸೇರಿಸುವ ಗೇರುಬೀಜ ಮತ್ತು ತುಪ್ಪದ ಪ್ರಮಾಣವನ್ನು ಮಿತಿಗೊಳಿಸಿ.",
      hi: "संतृप्त वसा (Saturated Fat) को नियंत्रित करने के लिए काजू और घी की मात्रा सीमित रखें।",
      ta: "அதிக கொழுப்பை தவிர்க்க முந்திரி மற்றும் நெய்யின் அளவை கட்டுப்படுத்தவும்.",
      te: "అధిక కొవ్వులను నివారించడానికి జీడిపప్పు మరియు నెయ్యి పరిమితంగా వేయాలి."
    },
    alternatives: "Idli, Pesarattu, Oats porridge",
    states: ["Tamil Nadu"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "kootu",
    name: {
      en: "Kootu (Vegetable and Lentil Stew with Coconut)",
      kn: "ಕೂಟು",
      hi: "कूटू (सब्जी और दाल का सूप)",
      ta: "கூட்டு",
      te: "కూటు"
    },
    category: "Leafy Greens",
    calories: 140,
    protein: 5.5,
    carbohydrates: 18,
    fat: 5.2,
    fiber: 4.5,
    iron: 2.8,
    calcium: 85,
    folate: 64,
    vitaminA: 120,
    vitaminB6: 0.12,
    vitaminB12: 0,
    vitaminC: 14,
    vitaminD: 0,
    vitaminE: 1.1,
    vitaminK: 12,
    magnesium: 45,
    potassium: 260,
    zinc: 0.9,
    sodium: 180,
    sugar: 1.0,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1 cup with lunch rice",
    safetyLevel: "Safe",
    explanation: {
      en: "A traditional Tamil stew using leafy greens, lentils, and local vegetables (like ash gourd or snake gourd) with a light coconut grind.",
      kn: "ಸೊಪ್ಪುಗಳು, ಬೇಳೆ ಮತ್ತು ಬೂದುಗುಂಬಳಕಾಯಿಯಂತಹ ಸ್ಥಳೀಯ ತರಕಾರಿಗಳೊಂದಿಗೆ ತೆಂಗಿನಕಾಯಿ ಸೇರಿಸಿ ಮಾಡುವ ಸಾಂಪ್ರದಾಯಿಕ ತಮಿಳು ಶೈಲಿಯ ಕೂಟು.",
      hi: "हरी पत्तेदार सब्जियों, दाल और स्थानीय सब्जियों (जैसे लौकी या कद्दू) से बना एक पारंपरिक तमिल व्यंजन।",
      ta: "கீரைகள், பருப்பு மற்றும் உள்ளூர் காய்கறிகள் (சாம்பல் பூசணி அல்லது புடலங்காய்) கொண்டு செய்யப்படும் பாரம்பரிய கூட்டு.",
      te: "ఆకుకూరలు, పప్పు మరియు కూరగాయలతో (బూడిద గుమ్మడి లేదా పొట్లకాయ) కొబ్బరి మసాలాతో చేసే సాంప్రదాయ తమిళ వంటకం."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Rich in folic acid, iron, and dietary fiber. Excellent for preventing prenatal anemia and supporting fetal organ development.",
      kn: "ಫೋಲಿಕ್ ಆಸಿಡ್, ಕಬ್ಬಿಣ ಮತ್ತು ನಾರಿನಂಶದಿಂದ ಸಮೃದ್ಧವಾಗಿದೆ. ರಕ್ತಹೀನತೆ ತಡೆಯಲು ಮತ್ತು ಮಗುವಿನ ಅಂಗಾಂಗಗಳ ಬೆಳವಣಿಗೆಗೆ ಇದು ಉತ್ತಮ.",
      hi: "फॉलिक एसिड, आयरन और फाइबर से भरपूर। रक्तहीनता (Anemia) से बचाने और शिशु के विकास में सहायक।",
      ta: "ஃபோலிக் அமிலம், இரும்பு மற்றும் நார்ச்சத்து நிறைந்தது. இரத்த சோகையைத் தடுக்கவும் குழந்தையின் வளர்ச்சிக்கும் நல்லது.",
      te: "ఫోలిక్ యాసిడ్, ఐరన్ మరియు ఫైబర్ పుష్కలంగా ఉంటాయి. రక్తహీనతను నివారించి, శిశువు అవయవాల అభివృద్ధికి తోడ్పడుతుంది."
    },
    risks: {
      en: "Ensure the vegetables are washed thoroughly to eliminate any soil-borne pathogens before cooking.",
      kn: "ಅಡುಗೆ ಮಾಡುವ ಮೊದಲು ಮಣ್ಣಿನ ಬ್ಯಾಕ್ಟೀರಿಯಾಗಳನ್ನು ನಿವಾರಿಸಲು ತರಕಾರಿಗಳನ್ನು ಚೆನ್ನಾಗಿ ತೊಳೆಯಿರಿ.",
      hi: "बनाने से पहले सब्जियों को अच्छी तरह धोएं ताकि मिट्टी के बैक्टीरिया खत्म हो सकें।",
      ta: "சமைப்பதற்கு முன் காய்கறிகளை நன்றாக கழுவவும்.",
      te: "కూరగాయలను వండే ముందు చాలా శుభ్రంగా కడగాలి."
    },
    alternatives: "Gongura Pappu, Cooked Spinach, Avial",
    states: ["Tamil Nadu"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "appam",
    name: {
      en: "Appam (Fermented Rice Pancake with Coconut)",
      kn: "ಆಪಂ",
      hi: "अप्पम",
      ta: "ஆப்பம்",
      te: "ఆప్పం"
    },
    category: "Breakfast",
    calories: 120,
    protein: 2.5,
    carbohydrates: 24,
    fat: 1.8,
    fiber: 1.1,
    iron: 0.6,
    calcium: 12,
    folate: 8,
    vitaminA: 0,
    vitaminB6: 0.04,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.2,
    vitaminK: 0.2,
    magnesium: 15,
    potassium: 78,
    zinc: 0.3,
    sodium: 120,
    sugar: 0.8,
    servingSize: "2 appams (100g)",
    recommendedQuantity: "2 pieces for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "Appam is a soft, fermented rice pancake with a spongy center and lacy edges. Extremely gentle on sensitive stomachs and easy to digest.",
      kn: "ಆಪಂ ಮೃದುವಾದ, ಹುದುಗಿಸಿದ ಅಕ್ಕಿ ಹಿಟ್ಟಿನ ದೋಸೆಯಾಗಿದ್ದು ಹೊಟ್ಟೆಗೆ ಹಿತಕರವಾಗಿದೆ ಮತ್ತು ಜೀರ್ಣಿಸಿಕೊಳ್ಳಲು ಸುಲಭವಾಗಿದೆ.",
      hi: "अप्पम एक नरम, खमीरयुक्त (Fermented) चावल का पैनकेक है। संवेदनशील पेट के लिए बहुत हल्का और पचाने में आसान।",
      ta: "ஆப்பம் ஒரு மென்மையான, புளித்த அரிசி மாவு உணவு. எளிதில் செரிமானமாகக்கூடியது, வயிற்றுக்கு இதமானது.",
      te: "ఆప్పం మెత్తటి, పులియబెట్టిన బియ్యపు పిండి వంటకం. సులభంగా జీర్ణమవుతుంది, గ్యాస్ సమస్యలను రానివ్వదు."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Fermentation increases vitamin B complex bioavailability. Soft texture is perfect for dealing with nausea.",
      kn: "ಹುದುಗುವಿಕೆಯು ವಿಟಮಿನ್ ಬಿ ಸಂಕೀರ್ಣದ ಲಭ್ಯತೆಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ. ಮೃದುವಾದ ವಿನ್ಯಾಸವು ವಾಕರಿಕೆಗೆ ಸೂಕ್ತವಾಗಿದೆ.",
      hi: "किण्वन (Fermentation) से विटामिन बी की मात्रा बढ़ती है। नरम बनावट मतली में राहत देती है।",
      ta: "புளிக்கவைப்பதால் வைட்டமின் பி சத்துக்கள் அதிகரிக்கும். குமட்டல் உள்ளவர்களுக்கு சாப்பிட எளிதானது.",
      te: "పులియబెట్టడం వల్ల విటమిన్ బి కాంప్లెక్స్ లభిస్తుంది. వికారంతో బాధపడేవారికి ఇది చాలా సులభంగా లోపలికి వెళ్తుంది."
    },
    risks: {
      en: "Avoid pairing it with heavy, spice-loaded curries or too much sweetened coconut milk.",
      kn: "ಇದರೊಂದಿಗೆ ಹೆಚ್ಚು ಮಸಾಲೆಯುಕ್ತ ಸಾರು ಅಥವಾ ಅತಿಯಾದ ಸಿಹಿ ತೆಂಗಿನ ಹಾಲನ್ನು ಸೇವಿಸಬೇಡಿ.",
      hi: "इसके साथ अत्यधिक मसालेदार कढ़ी या बहुत मीठा नारियल का दूध न लें।",
      ta: "அதிக காரமான குழம்பு அல்லது அதிக சர்க்கரை சேர்த்த தேங்காய் பால் குடிப்பதை தவிர்க்கவும்.",
      te: "దీనితో పాటు కారంగా ఉండే కూరలు లేదా ఎక్కువ చక్కెర కలిపిన కొబ్బరి పాలు తీసుకోకూడదు."
    },
    alternatives: "Idli, Puttu, Plain Dosa",
    states: ["Kerala", "Tamil Nadu", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "puttu",
    name: {
      en: "Puttu (Steamed Rice and Coconut cylinders)",
      kn: "ಪುಟ್ಟು",
      hi: "पुट्टु (उबले चावल और नारियल)",
      ta: "புட்டு",
      te: "పుట్టు"
    },
    category: "Breakfast",
    calories: 230,
    protein: 4.8,
    carbohydrates: 45,
    fat: 3.2,
    fiber: 2.4,
    iron: 0.9,
    calcium: 18,
    folate: 10,
    vitaminA: 0,
    vitaminB6: 0.05,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.4,
    vitaminK: 0.3,
    magnesium: 24,
    potassium: 115,
    zinc: 0.6,
    sodium: 95,
    sugar: 0.5,
    servingSize: "1 cup cooked (120g)",
    recommendedQuantity: "1 serving with ripe banana",
    safetyLevel: "Safe",
    explanation: {
      en: "Puttu is a steamed cylindrical layer of ground rice and grated coconut. It is oil-free and cooked purely with steam, making it highly safe and nutritious.",
      kn: "ಪುಟ್ಟು ಅಕ್ಕಿ ಹಿಟ್ಟು ಮತ್ತು ತುರಿದ ತೆಂಗಿನಕಾಯಿಯ ಹಬೆಯಲ್ಲಿ ಬೆಂದ ಸಿಲಿಂಡರ್ ಆಕಾರದ ತಿನಿಸು. ಇದು ಸಂಪೂರ್ಣ ಎಣ್ಣೆ ರಹಿತ ಹಾಗೂ ಸುರಕ್ಷಿತ ಆಹಾರವಾಗಿದೆ.",
      hi: "पुट्टु उबले हुए चावल के आटे और कद्दूकस किए हुए नारियल से बना एक तेल-मुक्त व्यंजन है, जो भाप में पकता है।",
      ta: "புட்டு என்பது அரிசி மாவு மற்றும் துருவிய தேங்காய் கொண்டு ஆவியில் வேகவைக்கப்படும் உணவு. எண்ணெய் இல்லாததால் மிகவும் ஆரோக்கியமானது.",
      te: "పుట్టు బియ్యప్పిండి మరియు కొబ్బరి తురుముతో ఆవిరిపై ఉడికించే నూనె లేని వంటకం. గర్భిణులకు చాలా సురಕ್ಷితమైనది."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Completely oil-free, highly nutritious, and yields clean complex carbohydrates for steady energy release.",
      kn: "ಸಂಪೂರ್ಣವಾಗಿ ಎಣ್ಣೆ ರಹಿತವಾಗಿದ್ದು, ದಿನವಿಡೀ ಸ್ಥಿರವಾದ ಶಕ್ತಿಯನ್ನು ನೀಡುವ ಕಾರ್ಬೋಹೈಡ್ರೇಟ್‌ಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.",
      hi: "पूरी तरह से तेल-मुक्त और दिनभर निरंतर ऊर्जा देने के लिए जटिल कार्बोहाइड्रेट से भरपूर।",
      ta: "முற்றிலும் எண்ணெய் இல்லாதது, நாள் முழுவதும் தேவையான ஆற்றலைத் தரும் சிக்கலான கார்போஹைட்ரேட்டுகளைக் கொண்டது.",
      te: "నూనె లేకుండా వండేది, రోజంతా అవసరమైన శక్తిని అందించే పిండిపదార్థాలు లభిస్తాయి."
    },
    risks: {
      en: "Ensure it is well steamed to avoid any dry rice flour causing throat irritation or constipation.",
      kn: "ಗಂಟಲು ಕೆರೆತ ಅಥವಾ ಮಲಬದ್ಧತೆಯನ್ನು ತಪ್ಪಿಸಲು ಹಿಟ್ಟು ಚೆನ್ನಾಗಿ ಬೆಂದಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
      hi: "सुनिश्चित करें कि यह अच्छी तरह भाप में पका हो ताकि सूखा आटा गले में खराश या कब्ज पैदा न करे।",
      ta: "வறண்ட மாவு தொண்டை எரிச்சல் அல்லது மலச்சிக்கலை ஏற்படுத்தாமல் இருக்க நன்றாக வெந்திருக்க வேண்டும்.",
      te: "పొడి పిండి వల్ల గొంతునొప్పి లేదా మలబద్ధకం రాకుండా బాగా ఆవిరి పట్టాలి."
    },
    alternatives: "Appam, Idli, Steamed ragi puttu",
    states: ["Kerala"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "avial",
    name: {
      en: "Avial (Mixed Vegetable Coconut Stew)",
      kn: "ಅವಿಯಲ್",
      hi: "अवियल (मिश्रित सब्जी)",
      ta: "அவியல்",
      te: "అవియల్"
    },
    category: "Traditional Recipes",
    calories: 160,
    protein: 3.8,
    carbohydrates: 14,
    fat: 10.5,
    fiber: 3.8,
    iron: 1.5,
    calcium: 65,
    folate: 32,
    vitaminA: 240,
    vitaminB6: 0.15,
    vitaminB12: 0,
    vitaminC: 18,
    vitaminD: 0,
    vitaminE: 1.6,
    vitaminK: 8.5,
    magnesium: 35,
    potassium: 290,
    zinc: 0.7,
    sodium: 140,
    sugar: 1.8,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1-2 cups with lunch",
    safetyLevel: "Safe",
    explanation: {
      en: "A nutrient-rich mix of local South Indian vegetables cooked with grated coconut, curd, and seasoned with cold-pressed coconut oil and curry leaves.",
      kn: "ತೆಂಗಿನಕಾಯಿ, ಮೊಸರು ಮತ್ತು ಕೊಬ್ಬರಿ ಎಣ್ಣೆಯಿಂದ ಮಾಡಿದ ವೈವಿಧ್ಯಮಯ ತರಕಾರಿಗಳ ಪೌಷ್ಟಿಕ ಮಿಶ್ರಣವಾಗಿದೆ.",
      hi: "ताजे नारियल, दही और नारियल तेल से पकी हुई मिश्रित हरी सब्जियों का एक पोषक तत्व-समृद्ध व्यंजन।",
      ta: "துருவிய தேங்காய், தயிர் மற்றும் தேங்காய் எண்ணெய் சேர்த்து சமைக்கப்படும் காய்கறிகளின் சத்தான கலவை.",
      te: "పచ్చి కొబ్బరి, పెరుగు మరియు కొబ్బరి నూనెతో కూరగాయల ముక్కలను ఉడికించి చేసే పౌష్టిక వంటకం."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Incredible array of vitamins and minerals due to mixed vegetables (carrot, beans, drumstick, pumpkin). Coconut oil provides medium-chain fatty acids.",
      kn: "ಕ್ಯಾರೆಟ್, ನುಗ್ಗೆಕಾಯಿ, ಕುಂಬಳಕಾಯಿಯಂತಹ ತರಕಾರಿಗಳಿಂದ ಅದ್ಭುತ ಜೀವಸತ್ವಗಳು ದೊರೆಯುತ್ತವೆ. ಕೊಬ್ಬರಿ ಎಣ್ಣೆಯು ಆರೋಗ್ಯಕರ ಕೊಬ್ಬನ್ನು ಒದಗಿಸುತ್ತದೆ.",
      hi: "गाजर, सहजन और कद्दू जैसी मिश्रित सब्जियों के कारण प्रचुर मात्रा में विटामिन। नारियल तेल से स्वस्थ वसा मिलती है।",
      ta: "கேரட், முருங்கைக்காய், பூசணி போன்ற காய்கறிகளிலிருந்து அதிக வைட்டமின்கள் கிடைக்கும். தேங்காய் எண்ணெய் ஆரோக்கியமான கொழுப்பை தரும்.",
      te: "క్యారెట్, ములక్కాడ, గుమ్మడికాయ వంటి కూరగాయల వల్ల విటమిన్లు లభిస్తాయి. కొబ్బరి నూనె ద్వారా మంచి కొవ్వులు అందుతాయి."
    },
    risks: {
      en: "Avoid vegetables that are unwashed or raw. Use fresh, hygienically prepared curd.",
      kn: "ತರಕಾರಿಗಳನ್ನು ಚೆನ್ನಾಗಿ ತೊಳೆಯಿರಿ. ತಾಜಾ ಮೊಸರನ್ನು ಮಾತ್ರ ಬಳಸಿ.",
      hi: "बिना धुली सब्जियों का प्रयोग न करें। ताजे दही का ही इस्तेमाल करें।",
      ta: "நன்றாக கழுவப்பட்ட காய்கறிகள் மற்றும் புதிய தயிரை மட்டுமே பயன்படுத்தவும்.",
      te: "కూరగాయలను శుభ్రంగా కడగాలి. పుల్లటి పెరుగు కాకుండా తాజా పెరుగు వాడాలి."
    },
    alternatives: "Kootu, Veg Stew, Poriyal",
    states: ["Kerala", "Tamil Nadu"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "pesarattu",
    name: {
      en: "Pesarattu (Whole Green Gram Dosa)",
      kn: "ಪೆಸರಟ್ಟು",
      hi: "पेसारेट्टु (मूंग दाल डोसा)",
      ta: "பெசரட்டு (பாசிப்பயறு தோசை)",
      te: "పెసరట్టు"
    },
    category: "Breakfast",
    calories: 220,
    protein: 12.5,
    carbohydrates: 34,
    fat: 4.2,
    fiber: 6.8,
    iron: 3.2,
    calcium: 48,
    folate: 110,
    vitaminA: 80,
    vitaminB6: 0.18,
    vitaminB12: 0,
    vitaminC: 3.2,
    vitaminD: 0,
    vitaminE: 0.9,
    vitaminK: 2.5,
    magnesium: 54,
    potassium: 280,
    zinc: 1.4,
    sodium: 160,
    sugar: 0.9,
    servingSize: "1 medium dosa (110g)",
    recommendedQuantity: "1-2 pieces for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "Pesarattu is a wholesome crepe made of green gram (moong dal). It has a high protein content and is rich in folate, which is critical for early pregnancy.",
      kn: "ಹೆಸರು ಕಾಳಿನಿಂದ ತಯಾರಿಸುವ ಪೆಸರಟ್ಟು ಪ್ರೋಟೀನ್ ಮತ್ತು ಫೋಲೇಟ್‌ನಿಂದ ಸಮೃದ್ಧವಾಗಿದೆ, ಇದು ಗರ್ಭಾವಸ್ಥೆಯ ಆರಂಭಿಕ ಹಂತದಲ್ಲಿ ಬಹಳ ಮುಖ್ಯವಾಗಿದೆ.",
      hi: "पेसारेट्टु मूंग दाल से बना एक पौष्टिक डोसा है। इसमें उच्च प्रोटीन और फोलेट होता है, जो प्रारंभिक गर्भावस्था के लिए बेहद आवश्यक है।",
      ta: "பாசிப்பயறால் செய்யப்படும் பெசரட்டு புரதமும் ஃபோலேட்டும் நிறைந்தது, இது ஆரம்பகால கர்ப்பத்திற்கு மிகவும் தேவையானது.",
      te: "పెసరట్టు పెసరపప్పుతో చేసే పోషకాలతో కూడిన దోశ. దీనిలో ప్రోటీన్ మరియు ఫోలేట్ ఎక్కువగా ఉంటాయి, ఇది గర్భధారణ ప్రారంభంలో ఎంతో అవసరం."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "High protein (12.5g) supports cell growth. Folate (110mcg) prevents neural tube defects in the growing baby.",
      kn: "ಹೆಚ್ಚಿನ ಪ್ರೋಟೀನ್ (೧೨.೫ ಗ್ರಾಂ) ಮಗುವಿನ ಜೀವಕೋಶಗಳ ಬೆಳವಣಿಗೆಗೆ ಸಹಕಾರಿ; ಫೋಲೇಟ್ ಮೆದುಳಿನ ವಿಕಾಸಕ್ಕೆ ಸಹಕಾರಿ.",
      hi: "उच्च प्रोटीन (12.5g) कोशिका विकास का समर्थन करता है। फोलेट (110mcg) शिशु के मस्तिष्क विकास के लिए महत्वपूर्ण है।",
      ta: "அதிக புரதம் (12.5g) வளர்ச்சிக்கு உதவும். ஃபோலேட் (110mcg) குழந்தையின் மூளை மற்றும் தண்டுவட வளர்ச்சிக்கு நல்லது.",
      te: "అధిక ప్రోటీన్ కణాల అభివృద్ధికి, ఫోలేట్ (110mcg) శిశువు మెదడు వైకల్యాలు రాకుండా కాపాడుతుంది."
    },
    risks: {
      en: "Ensure green gram is soaked and ground under clean conditions. Cook thoroughly with minimal oil.",
      kn: "ಹೆಸರು ಕಾಳನ್ನು ಸ್ವಚ್ಛವಾದ ನೀರಿನಲ್ಲಿ ನೆನೆಸಿ ರುಬ್ಬಿಕೊಳ್ಳಿ. ಕಡಿಮೆ ಎಣ್ಣೆಯಲ್ಲಿ ಚೆನ್ನಾಗಿ ಬೇಯಿಸಿ.",
      hi: "सुनिश्चित करें कि मूंग दाल को साफ पानी में भिगोया और पीसा गया हो। कम तेल में अच्छी तरह पकाएं।",
      ta: "பாசிப்பயறை சுத்தமான நீரில் ஊறவைத்து அரைக்கவும். குறைந்த எண்ணெயில் நன்றாக வேகவைக்கவும்.",
      te: "పెసలను శుభ్రమైన నీటిలో నానబెట్టాలి. తక్కువ నూనెతో బాగా కాల్చాలి."
    },
    alternatives: "Moong dal chilla, Idli, Rava Dosa",
    states: ["Andhra Pradesh"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "gongura_pappu",
    name: {
      en: "Gongura Pappu (Sorrel Leaves Toor Dal)",
      kn: "ಗೋಂಗೂರ ಬೇಳೆ ತೊವ್ವೆ (ಪುಂಡಿ ಸೊಪ್ಪು ಸಾರು)",
      hi: "गोंगूरा पप्पू (खट्टी भाजी की दाल)",
      ta: "கோங்குரா பருப்பு (புளிச்சக்கீரை பருப்பு)",
      te: "గోంగూర పప్పు"
    },
    category: "Leafy Greens",
    calories: 160,
    protein: 9.5,
    carbohydrates: 24,
    fat: 3.5,
    fiber: 4.8,
    iron: 4.2,
    calcium: 95,
    folate: 82,
    vitaminA: 180,
    vitaminB6: 0.15,
    vitaminB12: 0,
    vitaminC: 22,
    vitaminD: 0,
    vitaminE: 0.9,
    vitaminK: 18,
    magnesium: 55,
    potassium: 290,
    zinc: 1.1,
    sodium: 140,
    sugar: 0.8,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1 cup with steamed brown rice",
    safetyLevel: "Safe",
    explanation: {
      en: "A sour, tangy combination of iron-rich sorrel leaves (gongura) and protein-packed Toor dal. Highly effective for combating prenatal iron deficiencies.",
      kn: "ಕಬ್ಬಿಣದಂಶವಿರುವ ಪುಂಡಿ ಸೊಪ್ಪು (ಗೋಂಗೂರ) ಮತ್ತು ಪ್ರೋಟೀನ್ ಇರುವ ತೊಗರಿ ಬೇಳೆಯ ಹುಳಿ ಮಿಶ್ರಣ. ರಕ್ತಹೀನತೆ ನಿವಾರಿಸಲು ಇದು ಅತ್ಯುತ್ತಮ ಆಹಾರವಾಗಿದೆ.",
      hi: "आयरन से भरपूर गोंगूरा पत्तियां और प्रोटीन से भरपूर तूर दाल का एक खट्टा स्वादिष्ट संयोजन, जो एनीमिया से बचाता है।",
      ta: "இரும்புச்சத்து நிறைந்த புளிச்சக்கீரையும் புரதம் நிறைந்த துவரம்பருப்பும் சேர்ந்த கலவை. இரத்த சோகையை குணப்படுத்த பெரிதும் உதவும்.",
      te: "ఐరన్ పుష్కలంగా ఉండే గోంగూర ఆకులు మరియు ప్రోటీన్లు ఉండే కందిపప్పు కలిపి వండే రుచికరమైన పప్పు. రక్తహీనతను నివారిస్తుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Very high iron content (4.2mg) and Vitamin C (22mg) which dramatically boosts non-heme iron absorption.",
      kn: "ಅತಿ ಹೆಚ್ಚು ಕಬ್ಬಿಣದಂಶ (೪.೨ ಮಿಗ್ರಾಂ) ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಇದ್ದು, ಇದು ದೇಹ ಕಬ್ಬಿಣದಂಶವನ್ನು ಹೀರಿಕೊಳ್ಳಲು ನೆರವಾಗುತ್ತದೆ.",
      hi: "बहुत अधिक आयरन (4.2mg) और विटामिन सी (22mg) जो शरीर में आयरन के अवशोषण को काफी बढ़ा देता है।",
      ta: "அதிக இரும்புச்சத்து (4.2mg) மற்றும் வைட்டமின் சி (22mg) உள்ளது, இது இரும்புச்சத்தை உடல் உறிஞ்ச தூண்டும்.",
      te: "అధిక ఐరన్ (4.2mg) మరియు విటమిన్ సి (22mg) శరీరంలో ఐరన్ గ్రహణ శక్తిని అద్భుతంగా పెంచుతాయి."
    },
    risks: {
      en: "Slightly high sodium if seasoned with excess salt. Control oil tempering to prevent pregnancy acidity.",
      kn: "ಹೆಚ್ಚು ಉಪ್ಪು ಸೇರಿಸಿದರೆ ಸೋಡಿಯಂ ಹೆಚ್ಚಾಗುತ್ತದೆ. ಗ್ಯಾಸ್ಟ್ರಿಕ್ ಸಮಸ್ಯೆ ತಡೆಯಲು ಒಗ್ಗರಣೆಯಲ್ಲಿ ಎಣ್ಣೆ ಕಮ್ಮಿ ಇರಲಿ.",
      hi: "अधिक नमक डालने पर सोडियम बढ़ सकता है। एसिडिटी से बचने के लिए तड़के में तेल कम रखें।",
      ta: "அதிக உப்பு சேர்ப்பதை தவிர்க்கவும். நெஞ்செரிச்சலை தடுக்க தாளிக்கும் போது எண்ணெய் குறைவாக பயன்படுத்தவும்.",
      te: "ఉప్పు మరియు నూనె తక్కువగా వేయాలి. లేదంటే గర్భిణులకు గుండెల్లో మంట రావచ్చు."
    },
    alternatives: "Palak Pappu, Kootu, Tomato Pappu",
    states: ["Andhra Pradesh"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "pulihora",
    name: {
      en: "Pulihora (Andhra Tamarind Rice)",
      kn: "ಪುಲಿಹೋರ (ಹುಳಿ ಚಿತ್ರಾನ್ನ)",
      hi: "पुलिहोरा (इमली चावल)",
      ta: "புளியோதரை",
      te: "పులిహోర"
    },
    category: "Traditional Recipes",
    calories: 260,
    protein: 4.5,
    carbohydrates: 48,
    fat: 5.8,
    fiber: 2.1,
    iron: 1.4,
    calcium: 28,
    folate: 14,
    vitaminA: 15,
    vitaminB6: 0.06,
    vitaminB12: 0,
    vitaminC: 4.5,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 2.0,
    magnesium: 24,
    potassium: 135,
    zinc: 0.7,
    sodium: 220,
    sugar: 0.6,
    servingSize: "1 plate (150g)",
    recommendedQuantity: "Small portion with lunch curd",
    safetyLevel: "Safe in Moderation",
    explanation: {
      en: "A traditional tangy rice seasoned with tamarind paste, peanuts, and curry leaves. The sourness helps alleviate nausea and metallic taste in the mouth.",
      kn: "ಹುಣಿಸೇಹಣ್ಣು, ಕಡಲೆಕಾಯಿ ಮತ್ತು ಕರಿಬೇವು ಸೇರಿಸಿದ ಹುಳಿ ಚಿತ್ರಾನ್ನ. ಇದರ ಹುಳಿಯು ಗರ್ಭಿಣಿಯರ ವಾಕರಿಕೆ ಮತ್ತು ಬಾಯಿಯ ರುಚಿಗೆ ಒಳ್ಳೆಯದು.",
      hi: "इमली, मूंगफली और करी पत्ते से तैयार खट्टा चावल। यह गर्भावस्था में होने वाली मतली और मुंह का बेस्वादपन दूर करता है।",
      ta: "புளி, வேர்க்கடலை மற்றும் கறிவேப்பிலை கொண்டு செய்யப்படும் புளிப்பு சாதம். கர்ப்பகால குமட்டலை தணிக்கவும் வாய்க்கு ರುಚಿ தரவும் உதவும்.",
      te: "చింతపండు, పల్లీలు మరియు కరివేపాకుతో చేసే పుల్లటి అన్నం. ఇది నోటికి రుచిని ఇవ్వడమే కాకుండా వికారాన్ని తగ్గిస్తుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Peanuts add folate and protein; curry leaves supply vitamin A. Sour tamarind stimulates appetite and improves digestion.",
      kn: "ಕಡಲೆಕಾಯಿಯು ಪ್ರೋಟೀನ್ ಮತ್ತು ಫೋಲೇಟ್ ನೀಡುತ್ತದೆ; ಹುಣಿಸೇಹಣ್ಣು ಹಸಿವನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ ಮತ್ತು ಜೀರ್ಣಕ್ರಿಯೆಗೆ ನೆರವಾಗುತ್ತದೆ.",
      hi: "मूंगफली से प्रोटीन और फोलेट मिलता है। इमली भूख बढ़ाती है और पाचन में सुधार करती है।",
      ta: "வேர்க்கடலை புரதத்தை தரும்; புளி பசியைத் தூண்டி செரிமானத்தை மேம்படுத்தும்.",
      te: "పల్లీల ద్వారా ప్రోటీన్, ఫోలేట్ అందుతాయి. చింతపండు ఆకలిని పెంచుతుంది."
    },
    risks: {
      en: "High carbohydrate load. Should be eaten in moderation, especially if suffering from Gestational Diabetes.",
      kn: "ಹೆಚ್ಚಿನ ಪಿಷ್ಟ ಇರುವುದರಿಂದ ಸಕ್ಕರೆ ಪ್ರಮಾಣ ಹೆಚ್ಚಾಗಬಹುದು. ಮಧುಮೇಹ ಇದ್ದವರು ಮಿತವಾಗಿ ತಿನ್ನಬೇಕು.",
      hi: "कार्बोहाइड्रेट की उच्च मात्रा। गर्भकालीन मधुमेह होने पर इसे बहुत सीमित मात्रा में ही खाएं।",
      ta: "அதிக கார்போஹைட்ரேட் உள்ளது. நீரிழிவு நோய் உள்ளவர்கள் அளவோடு சாப்பிட வேண்டும்.",
      te: "పిండిపదార్థాలు ఎక్కువ. గర్భధారణ మధుమేహం ఉంటే దీనిని చాలా పరిమितంగా తినాలి."
    },
    alternatives: "Lemon Rice, Curd Rice, Veg Pulav",
    states: ["Andhra Pradesh", "Telangana"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1556017487-52cd68a29dee?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "sarva_pindi",
    name: {
      en: "Sarva Pindi (Telangana Rice Pancake)",
      kn: "ಸರ್ವ ಪಿಂಡಿ",
      hi: "सर्व पिंडी (चावल और दाल का चिल्ला)",
      ta: "சர்வ பிண்டி",
      te: "సర్వ పిండి"
    },
    category: "Breakfast",
    calories: 230,
    protein: 4.8,
    carbohydrates: 42,
    fat: 4.5,
    fiber: 3.1,
    iron: 1.5,
    calcium: 35,
    folate: 15,
    vitaminA: 10,
    vitaminB6: 0.07,
    vitaminB12: 0,
    vitaminC: 1.0,
    vitaminD: 0,
    vitaminE: 0.6,
    vitaminK: 0.8,
    magnesium: 28,
    potassium: 125,
    zinc: 0.8,
    sodium: 180,
    sugar: 0.4,
    servingSize: "1 piece (100g)",
    recommendedQuantity: "1 piece for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "A savory pancake made of rice flour, chana dal, peanuts, and sesame seeds. A traditional Telangana snack that is rich in minerals and highly satisfying.",
      kn: "ಅಕ್ಕಿ ಹಿಟ್ಟು, ಕಡಲೆಬೇಳೆ, ಕಡಲೆಕಾಯಿ ಮತ್ತು ಎಳ್ಳು ಬೀಜಗಳಿಂದ ತಯಾರಿಸಿದ ಸಾಂಪ್ರದಾಯಿಕ ತೆಲಂಗಾಣ ಶೈಲಿಯ ಖಾರದ ರೊಟ್ಟಿ.",
      hi: "चावल के आटे, चना दाल, मूंगफली और तिल से बना एक नमकीन चिल्ला। यह खनिज तत्वों से भरपूर और पेट भरने वाला भोजन है।",
      ta: "அரிசி மாவு, கடலைப்பருப்பு, வேர்க்கடலை மற்றும் எள் கொண்டு செய்யப்படும் கார அடை. தாதுக்கள் நிறைந்த ஆரோக்கியமான உணவு.",
      te: "బియ్యప్పిండి, శనగపప్పు, పల్లీలు మరియు నువ్వులతో చేసే సాంప్రదాయ తెలంగాణ రొట్టె. ఎంతో రుచికరమైనది, ఖనిజ లవణాలు కలది."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Sesame and peanuts provide essential zinc and calcium; slow-cooked texture is highly satisfying and delicious.",
      kn: "ಎಳ್ಳು ಮತ್ತು ಕಡಲೆಕಾಯಿಯು ಜಿಂಕ್ ಮತ್ತು ಕ್ಯಾಲ್ಸಿಯಂ ಒದಗಿಸುತ್ತದೆ; ಇದು ಹಸಿವನ್ನು ಚೆನ್ನಾಗಿ ನೀಗಿಸುತ್ತದೆ.",
      hi: "तिल और मूंगफली से जिंक और कैल्शियम मिलता है। यह काफी समय तक भूख को शांत रखता है।",
      ta: "எள் மற்றும் வேர்க்கடலை துத்தநாகம் மற்றும் கால்சியத்தை தரும். நீண்ட நேரம் பசியை கட்டுப்படுத்தும்.",
      te: "నువ్వులు మరియు పల్లీల వల్ల జింక్, కాల్షియం లభిస్తాయి. తిన్న తర్వాత చాలా సేపు ఆకలి వేయదు."
    },
    risks: {
      en: "Can become dry if overcooked. Ensure it is soft to prevent difficulty in chewing and heartburn.",
      kn: "ಹೆಚ್ಚು ಬೇಯಿಸಿದರೆ ಒಣಗಬಹುದು. ಸುಲಭವಾಗಿ ಅಗಿಯಲು ಮೃದುವಾಗಿರುವಾಗಲೆ ತೆಗೆಯಿರಿ.",
      hi: "ज्यादा पकाने पर यह कड़ा हो सकता है। इसे थोड़ा नरम ही रखें ताकि चबाने में आसानी हो।",
      ta: "அதிகம் வெந்தால் மொறுமொறுப்பாகிவிடும். நெஞ்செரிச்சலை தவிர்க்க மென்மையாக இருக்கும் போது சாப்பிடவும்.",
      te: "ఎక్కువగా కాలితే గట్టిపడుతుంది. సులభంగా నమలడానికి వీలుగా మెత్తగా కాల్చుకోవాలి."
    },
    alternatives: "Akki Roti, Pesarattu, Dosa",
    states: ["Telangana"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "jonna_roti",
    name: {
      en: "Jonna Roti (Sorghum Millet Flatbread)",
      kn: "ಜೋಳದ ರೊಟ್ಟಿ",
      hi: "ज्वार की रोटी (जोन्ना रोट्टे)",
      ta: "சோள ரொட்டி",
      te: "జొన్న రొట్టె"
    },
    category: "Millets",
    calories: 210,
    protein: 6.5,
    carbohydrates: 44,
    fat: 1.9,
    fiber: 6.2,
    iron: 2.8,
    calcium: 30,
    folate: 22,
    vitaminA: 0,
    vitaminB6: 0.16,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.2,
    magnesium: 64,
    potassium: 215,
    zinc: 1.2,
    sodium: 8,
    sugar: 0.5,
    servingSize: "1 roti (80g)",
    recommendedQuantity: "1-2 rotis for lunch",
    safetyLevel: "Safe",
    explanation: {
      en: "A traditional gluten-free flatbread made from sorghum (jowar). Extremely beneficial for managing blood sugar levels and highly recommended for gestational diabetes.",
      kn: "ಜೋಳದ ಹಿಟ್ಟಿನಿಂದ ತಯಾರಿಸಿದ ಸಾಂಪ್ರದಾಯಿಕ ಗ್ಲುಟನ್-ಮುಕ್ತ ರೊಟ್ಟಿ. ರಕ್ತದ ಸಕ್ಕರೆ ಪ್ರಮಾಣವನ್ನು ನಿಯಂತ್ರಿಸಲು ಮತ್ತು ಮಧುಮೇಹಕ್ಕೆ ಅತ್ಯುತ್ತಮ ಆಹಾರ.",
      hi: "ज्वार से बनी पारंपरिक ग्लूटेन-मुक्त रोटी। यह ब्लड शुगर को नियंत्रित करने में सहायक है और गर्भकालीन मधुमेह में अत्यधिक अनुशंसित है।",
      ta: "சோள மாவில் செய்யப்படும் குளுட்டன் இல்லாத ரொட்டி. இரத்த சர்க்கரை அளவை பராமரிக்கவும் கர்ப்பகால நீரிழிவுக்கும் மிகவும் நல்லது.",
      te: "జొన్నలతో చేసే సాంప్రదాయ గ్లూటెన్ రహిత రొట్టె. రక్తంలో చక్కర శాతాన్ని నియంత్రించడానికి, మధుమేహం ఉన్న గర్భిణులకు ఎంతో మేలు చేస్తుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Completely gluten-free; very low glycemic index prevents glucose spikes. Excellent dietary fiber content.",
      kn: "ಸಂಪೂರ್ಣ ಗ್ಲುಟನ್-ಮುಕ್ತ; ಕಡಿಮೆ ಗ್ಲೈಸೆಮಿಕ್ ಇಂಡೆಕ್ಸ್ ಸಕ್ಕರೆ ಏರಿಕೆಯನ್ನು ತಡೆಯುತ್ತದೆ ಮತ್ತು ಅತ್ಯುತ್ತಮ ನಾರಿನಂಶ ಹೊಂದಿದೆ.",
      hi: "पूरी तरह से ग्लूटेन-मुक्त; कम ग्लाइसेमिक इंडेक्स ब्लड शुगर बढ़ने से रोकता है। फाइबर का अच्छा स्रोत।",
      ta: "முற்றிலும் குளுட்டன் இல்லாதது; குறைந்த கிளைசெமிக் குறியீடு சர்க்கரை அதிகரிப்பை தடுக்கும். நார்சத்து அதிகம்.",
      te: "పూర్తిగా గ్లూటెన్ రహితమైనది; తక్కువ గ్లైసిమిక్ ఇండెక్స్ వల్ల బ్లడ్ షుగర్ పెరగదు. పీచు పదార్థం ఎక్కువ."
    },
    risks: {
      en: "None. Sorghum is highly safe; consume with clean water and a fiber-rich curry.",
      kn: "ಯಾವುದೇ ಅಡ್ಡಪರಿಣಾಮಗಳಿಲ್ಲ; ಜೋಳವು ಅತ್ಯಂತ ಸುರಕ್ಷಿತವಾಗಿದ್ದು, ತರಕಾರಿ ಸಾರಿನೊಂದಿಗೆ ಸವಿಯಿರಿ.",
      hi: "कोई जोखिम नहीं। ज्वार अत्यधिक सुरक्षित है; इसे हरी सब्जी या दाल के साथ खाएं।",
      ta: "எந்த அபாயமும் இல்லை. சோளம் மிகவும் பாதுகாப்பானது; காய்கறி குழம்புடன் சேர்த்து சாப்பிடலாம்.",
      te: "ఎలాంటి ప్రమాదం లేదు. జొన్నలు చాలా సురಕ್ಷితం; దీనిని ఆకుకూరలు లేదా పప్పుతో తినవచ్చు."
    },
    alternatives: "Ragi Mudde, Bajra Roti, Wheat Chapati",
    states: ["Telangana"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "idli_sambar",
    name: {
      en: "Idli with Sambar (Steamed Rice Cakes)",
      kn: "ಇಡ್ಲಿ ಮತ್ತು ಸಾಂಬಾರ್",
      hi: "इडली और सांभर",
      ta: "இட்லி மற்றும் சாம்பார்",
      te: "ఇడ్లీ మరియు సాம்பార్"
    },
    category: "Breakfast",
    calories: 180,
    protein: 6.5,
    carbohydrates: 34,
    fat: 2.1,
    fiber: 4.8,
    iron: 1.8,
    calcium: 36,
    folate: 32,
    vitaminA: 45,
    vitaminB6: 0.12,
    vitaminB12: 0,
    vitaminC: 4.0,
    vitaminD: 0,
    vitaminE: 0.4,
    vitaminK: 1.2,
    magnesium: 38,
    potassium: 195,
    zinc: 1.0,
    sodium: 240,
    sugar: 0.5,
    servingSize: "2 idlis with 1 cup sambar",
    recommendedQuantity: "2-3 idlis for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "Steamed fermented rice and lentil cakes. Easily digestible, virtually fat-free, and contains balanced carbs and proteins.",
      kn: "ಹಬೆಯಲ್ಲಿ ಬೇಯಿಸಿದ ಮತ್ತು ಹುದುಗಿಸಿದ ಅಕ್ಕಿ-ಉದ್ದಿನ ಹಿಟ್ಟಿನ ಇಡ್ಲಿ. ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗುವ, ಶೂನ್ಯ ಕೊಬ್ಬಿನಂಶದ ಆರೋಗ್ಯಕರ ಆಹಾರ.",
      hi: "भाप में पके खमीरयुक्त चावल और दाल के केक। आसानी से पचने वाले, फैट-मुक्त, और संतुलित कार्ब्स व प्रोटीन से भरपूर।",
      ta: "ஆவியில் வேகவைக்கப்படும் இட்லி எளிதில் செரிமானமாகக்கூடியது, கொழுப்பு இல்லாதது, உடலுக்கு தேவையான மாவுச்சத்தும் புரதமும் கொண்டது.",
      te: "ఆవిరిపై ఉడికించే ఇడ్లీలు సులభంగా జీర్ణమవుతాయి, అసలు కొవ్వు ఉండదు, కార్బోహైడ్రేట్లు మరియు ప్రోటీన్లు సమానంగా అందుతాయి."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Fermentation enhances B-vitamin synthesis. Soft steaming process preserves nutrients and ensures zero harmful pathogens.",
      kn: "ಹುದುಗುವಿಕೆಯು ಬಿ-ಜೀವಸತ್ವಗಳನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ. ಹಬೆಯಲ್ಲಿ ಬೇಯಿಸುವುದರಿಂದ ಪೋಷಕಾಂಶಗಳು ನಾಶವಾಗುವುದಿಲ್ಲ.",
      hi: "किण्वन विटामिन बी को बढ़ाता है। भाप में पकाने से पोषक तत्व सुरक्षित रहते हैं और कीटाणु नष्ट होते हैं।",
      ta: "புளிக்கவைப்பதால் வைட்டமின் ಬಿ அதிகரிக்கும். ஆவியில் வேகவைப்பதால் சத்துக்கள் வீணாகாது.",
      te: "పులియబెట్టడం వల్ల విటమిన్ బి లభిస్తుంది. ఆవిరిపై ఉడికించడం వల్ల బ్యాక్టీరియాలు నశిస్తాయి."
    },
    risks: {
      en: "Sambar salt content should be monitored if suffering from Gestational Hypertension.",
      kn: "ರಕ್ತದೊತ್ತಡ ಇದ್ದರೆ ಸಾಂಬಾರ್‌ನಲ್ಲಿ ಉಪ್ಪಿನ ಪ್ರಮಾಣ ಕಡಿಮೆ ಇರಲಿ.",
      hi: "उच्च रक्तचाप होने पर सांभर में नमक की मात्रा कम रखें।",
      ta: "இரத்த அழுத்தம் உள்ளவர்கள் சாம்பாரில் உப்பு குறைவாக சேர்க்க வேண்டும்.",
      te: "రక్తపోటు ఉన్న గర్భిణులు సాంబారులో ఉప్పు శాతం తగ్గించాలి."
    },
    alternatives: "Appam, Puttu, Steamed Ragi Idli",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "dosa",
    name: {
      en: "Dosa (Fermented Rice Crepe)",
      kn: "ದೋಸೆ",
      hi: "डोसा",
      ta: "தோசை",
      te: "దోశ"
    },
    category: "Breakfast",
    calories: 160,
    protein: 3.8,
    carbohydrates: 32,
    fat: 2.1,
    fiber: 1.8,
    iron: 0.9,
    calcium: 20,
    folate: 12,
    vitaminA: 0,
    vitaminB6: 0.06,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 0.4,
    magnesium: 18,
    potassium: 110,
    zinc: 0.6,
    sodium: 110,
    sugar: 0.3,
    servingSize: "1 plain dosa (90g)",
    recommendedQuantity: "1-2 dosas for breakfast",
    safetyLevel: "Safe",
    explanation: {
      en: "A crispy fermented crepe made of rice and black lentils. Widely popular and a rich source of clean energy.",
      kn: "ಅಕ್ಕಿ ಮತ್ತು ಉದ್ದಿನ ಬೇಳೆಯಿಂದ ತಯಾರಿಸಿದ ಗರಿಗರಿಯಾದ ದೋಸೆ. ಇದು ಇಡೀ ದಕ್ಷಿಣ ಭಾರತದಲ್ಲಿ ಜನಪ್ರಿಯ ಮತ್ತು ಉತ್ತಮ ಶಕ್ತಿಯ ಮೂಲವಾಗಿದೆ.",
      hi: "चावल और उड़द की दाल से बना कुरकुरा खमीरयुक्त डोसा। अत्यधिक लोकप्रिय और ऊर्जा का बेहतरीन स्रोत।",
      ta: "அரிசி மற்றும் உளுந்தால் செய்யப்படும் மொறுமொறுப்பான தோசை. தென்னிந்தியாவில் மிகவும் பிரபலமான காலை உணவு.",
      te: "బియ్యం మరియు మినప్పప్పుతో చేసే కరకరలాడే దోశ. శరీరానికి మంచి శక్తిని ఇస్తుంది."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Rich in easily assimilable carbs. Fermentation improves digestibility and mineral absorption.",
      kn: "ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗುವ ಕಾರ್ಬೋಹೈಡ್ರೇಟ್‌ಗಳಿವೆ. ಜೀರ್ಣಕ್ರಿಯೆ ಮತ್ತು ಖನಿಜಗಳ ಹೀರಿಕೊಳ್ಳುವಿಕೆಯನ್ನು ಸುಧಾರಿಸುತ್ತದೆ.",
      hi: "आसानी से पचने वाले कार्बोहाइड्रेट। खनिज अवशोषण में मदद करता है।",
      ta: "எளிதில் ஜீரணமாகும் மாவுச்சத்து கொண்டது. தாதுக்களை உடல் உறிஞ்ச உதவும்.",
      te: "సులభంగా జీర్ణమవుతుంది. శరీరంలో ఖనిజాల గ్రహణ శక్తిని పెంచుతుంది."
    },
    risks: {
      en: "Avoid adding excess butter or oil during roasting. Potato stuffing (Masala Dosa) should be limited in GDM.",
      kn: "ಹೆಚ್ಚು ಬೆಣ್ಣೆ ಅಥವಾ ಎಣ್ಣೆ ಹಾಕಿ ಬೇಯಿಸಬೇಡಿ. ಮಧುಮೇಹ ಇದ್ದರೆ ಆಲೂಗಡ್ಡೆ ಪಲ್ಯ (ಮಸಾಲೆ ದೋಸೆ) ಕಡಿಮೆ ಮಾಡಿ.",
      hi: "बनाते समय अधिक मक्खन या तेल न डालें। मधुमेह होने पर आलू का मसाला (मसाला डोसा) सीमित करें।",
      ta: "நெய் அல்லது எண்ணெய் அதிகம் சேர்ப்பதை தவிர்க்கவும். நீரிழிவு இருந்தால் உருளைக்கிழங்கு மசாலாவை தவிர்க்கவும்.",
      te: "కాల్చేటప్పుడు ఎక్కువ నూనె కానీ బటర్ కానీ వేయకూడదు. మధుమేహం ఉంటే ఆలు కూర (మసాలా దోశ) తగ్గించాలి."
    },
    alternatives: "Idli, Pesarattu, Rava Idli",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "morungai_keerai_soup",
    name: {
      en: "Moringa Leaf Soup (Nugge Keerai)",
      kn: "ನುಗ್ಗೆ ಸೊಪ್ಪಿನ ಸೂಪ್",
      hi: "सहजन के पत्तों का सूप",
      ta: "முருங்கைக் கீரை சூப்",
      te: "మునగాకు సూప్"
    },
    category: "Healthy Drinks",
    calories: 65,
    protein: 4.2,
    carbohydrates: 8.5,
    fat: 1.5,
    fiber: 3.8,
    iron: 4.8,
    calcium: 185,
    folate: 78,
    vitaminA: 320,
    vitaminB6: 0.22,
    vitaminB12: 0,
    vitaminC: 45,
    vitaminD: 0,
    vitaminE: 2.1,
    vitaminK: 35,
    magnesium: 48,
    potassium: 310,
    zinc: 0.8,
    sodium: 95,
    sugar: 0.8,
    servingSize: "1 bowl (200ml)",
    recommendedQuantity: "1 bowl 3-4 times a week",
    safetyLevel: "Safe",
    explanation: {
      en: "Moringa leaves boiled with mild spices. A highly potent nutritional elixir for prenatal care, exceptionally rich in Iron, Calcium, and Vitamin A.",
      kn: "ನುಗ್ಗೆ ಸೊಪ್ಪನ್ನು ಸಾಂಬಾರ ಪದಾರ್ಥಗಳೊಂದಿಗೆ ಕುದಿಸಿ ಮಾಡುವ ಸೂಪ್. ಕಬ್ಬಿಣ, ಕ್ಯಾಲ್ಸಿಯಂ ಮತ್ತು ವಿಟಮಿನ್ ಎ ಇಂದ ಸಮೃದ್ಧವಾಗಿದ್ದು ಗರ್ಭಿಣಿಯರಿಗೆ ವರದಾನವಾಗಿದೆ.",
      hi: "सहजन की पत्तियों को हल्के मसालों के साथ उबालकर बनाया गया सूप। आयरन, कैल्शियम और विटामिन ए से भरपूर एक जादुई पेय।",
      ta: "முருங்கைக்கீரையை மிதமான மசாலாவுடன் கொதிக்க வைத்து செய்யப்படும் சூப். இரும்பு, கால்சியம் மற்றும் வைட்டமின் ஏ நிறைந்த ஒரு சத்தான பானம்.",
      te: "మునగాకులను తక్కువ మసాలాలతో ఉడికించి చేసే సూప్. ఐరన్, కాల్షియం మరియు విಟమిన్ ఎ పుష్కలంగా ఉండే ఒక అద్భుతమైన పౌష్టిక ఆహారం."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "Spectacular iron content (4.8mg) completely cures prenatal anemia. High calcium supports baby's bone and tooth buds.",
      kn: "ಅದ್ಭುತ ಕಬ್ಬಿಣದಂಶವು ರಕ್ತಹೀನತೆಯನ್ನು ಗುಣಪಡಿಸುತ್ತದೆ. ಹೆಚ್ಚಿನ ಕ್ಯಾಲ್ಸಿಯಂ ಮಗುವಿನ ಹಲ್ಲಿನ ಮತ್ತು ಮೂಳೆಗಳ ಬೆಳವಣಿಗೆಗೆ ಸಹಕಾರಿ.",
      hi: "अद्भुत आयरन की मात्रा एनीमिया को ठीक करती है। उच्च कैल्शियम शिशु के हड्डियों के विकास में मदद करता है।",
      ta: "அதிசயிக்கத்தக்க இரும்புச்சத்து இரத்த சோகையை குணப்படுத்தும். கால்சியம் குழந்தையின் எலும்பு வளர்ச்சிக்கு உதவும்.",
      te: "అద్భుతమైన ఐరన్ శాతం రక్తహీనతను నయం చేస్తుంది. అధిక కాల్షియం శిశువు ఎముకల ఎదుగుదలకు సహాయపడుతుంది."
    },
    risks: {
      en: "Do not add excessive pepper or hot spices as they may trigger acidity or heartburn.",
      kn: "ಅತಿಯಾದ ಕಾಳುಮೆಣಸು ಅಥವಾ ಖಾರವಾದ ಮಸಾಲೆ ಸೇರಿಸಬೇಡಿ, ಇದು ಗ್ಯಾಸ್ಟ್ರಿಕ್ ಉಂಟುಮಾಡಬಹುದು.",
      hi: "अधिक काली मिर्च या तीखे मसालों का प्रयोग न करें, क्योंकि इससे सीने में जलन हो सकती है।",
      ta: "அதிக மிளகு அல்லது காரமான மசாலாக்கள் சேர்ப்பதை தவிர்க்கவும், இது நெஞ்செரிச்சலை உண்டாக்கும்.",
      te: "మిరియాల పొడి లేదా కారం ఎక్కువగా వేయకూడదు, లేదంటే గుండెల్లో మంట రావచ్చు."
    },
    alternatives: "Spinach Soup, Tomato Soup, Drumstick Soup",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1547592165-e1d17eff60ab?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "curd_yogurt",
    name: {
      en: "Curd (Fresh Homemade Yogurt)",
      kn: "ತಾಜಾ ಮೊಸರು",
      hi: "दही (Curd)",
      ta: "தயிர்",
      te: "పెరుగు"
    },
    category: "Dairy",
    calories: 60,
    protein: 3.5,
    carbohydrates: 4.7,
    fat: 3.2,
    fiber: 0,
    iron: 0.1,
    calcium: 120,
    folate: 11,
    vitaminA: 27,
    vitaminB6: 0.04,
    vitaminB12: 0.4,
    vitaminC: 0.5,
    vitaminD: 0.1,
    vitaminE: 0.1,
    vitaminK: 0.2,
    magnesium: 12,
    potassium: 155,
    zinc: 0.6,
    sodium: 46,
    sugar: 4.0,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1-2 cups daily",
    safetyLevel: "Safe",
    explanation: {
      en: "Probiotic-rich fresh curd helps maintain gut microbiome balance, improves digestion, and delivers high-quality calcium for skeletal development.",
      kn: "ಪ್ರೋಬಯಾಟಿಕ್ ಸಮೃದ್ಧವಾಗಿರುವ ಮೊಸರು ಜೀರ್ಣಕ್ರಿಯೆಯನ್ನು ಸುಧಾರಿಸುತ್ತದೆ ಮತ್ತು ಮಗುವಿನ ಮೂಳೆಗಳ ಬೆಳವಣಿಗೆಗೆ ಉತ್ತಮ ಕ್ಯಾಲ್ಸಿಯಂ ನೀಡುತ್ತದೆ.",
      hi: "प्रोबायोटिक्स से भरपूर दही पाचन क्रिया को दुरुस्त रखता है और शिशु की हड्डियों के विकास के लिए कैल्शियम प्रदान करता है।",
      ta: "ப்ரோபயாடிக் நிறைந்த தயிர் செரிமானத்தை மேம்படுத்துவதோடு குழந்தையின் எலும்பு வளர்ச்சிக்கு தேவையான கால்சியத்தையும் வழங்கும்.",
      te: "మంచి బ్యాక్టీరియా (ప్రోబయోటిక్స్) కలిగిన పెరుగు జీర్ణక్రియను మెరుగుపరుస్తుంది మరియు ఎముకల ఎదుగుదలకు కాల్షియం అందిస్తుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Probiotics relieve pregnancy-related bloating and constipation; exceptional calcium density.",
      kn: "ಮೊಸರು ಗರ್ಭಿಣಿಯರಲ್ಲಿ ಹೊಟ್ಟೆ ಉಬ್ಬರ ಮತ್ತು ಮಲಬದ್ಧತೆಯನ್ನು ನಿವಾರಿಸುತ್ತದೆ; ಕ್ಯಾಲ್ಸಿಯಂನಿಂದ ಅತ್ಯುತ್ತಮವಾಗಿದೆ.",
      hi: "कब्ज और गैस की समस्या से राहत देता है; कैल्शियम का बेहतरीन स्रोत।",
      ta: "மலச்சிக்கல் மற்றும் வயிறு உப்பசம் போன்ற பிரச்சனைகளை தீர்க்கும்; கால்சியம் நிறைந்தது.",
      te: "మలబద్ధకం మరియు కడుపు ఉబ్బరం తగ్గిస్తుంది; కాల్షియం ఎక్కువగా లభిస్తుంది."
    },
    risks: {
      en: "Avoid sour, stale, or unpasteurized store curd. Opt for freshly set home curd.",
      kn: "ಹುಳಿ ಬಂದ ಅಥವಾ ಹಳೆಯ ಮೊಸರನ್ನು ಬಳಸಬೇಡಿ. ಮನೆಯಲ್ಲಿಯೇ ಮಾಡಿದ ತಾಜಾ ಮೊಸರು ಉತ್ತಮ.",
      hi: "खट्टा या बासी दही न खाएं। हमेशा ताजा जमा हुआ दही ही लें।",
      ta: "புளித்த அல்லது பழைய தயிரை தவிர்க்கவும். வீட்டில் உறை ஊற்றிய புதிய தயிர் சிறந்தது.",
      te: "పుల్లటి లేదా నిల్వ పెరుగు తినకూడదు. ఇంట్లో తోడుపెట్టిన తాజా పెరుగు తినాలి."
    },
    alternatives: "Buttermilk, Paneer, Plant-based yogurt",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "sesame_chikki",
    name: {
      en: "Sesame Chikki (Ellu Mitai)",
      kn: "ಎಳ್ಳು ಚಿಕ್ಕಿ",
      hi: "तिल चिक्की",
      ta: "எள்ளு மிட்டாய்",
      te: "నువ్వుల చిక్కి"
    },
    category: "Seeds",
    calories: 150,
    protein: 3.2,
    carbohydrates: 18,
    fat: 8.5,
    fiber: 1.5,
    iron: 2.8,
    calcium: 180,
    folate: 15,
    vitaminA: 0,
    vitaminB6: 0.12,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.5,
    vitaminK: 0.2,
    magnesium: 62,
    potassium: 95,
    zinc: 1.1,
    sodium: 45,
    sugar: 14.5,
    servingSize: "1 piece (30g)",
    recommendedQuantity: "1 piece after week 12 (Trimester 2 & 3)",
    safetyLevel: "Safe in Moderation",
    explanation: {
      en: "A sweet snack made of sesame seeds and jaggery. Sesame contains excellent calcium, but is traditionally restricted in the 1st Trimester (<12 weeks) due to mild uterine stimulation properties.",
      kn: "ಎಳ್ಳು ಮತ್ತು ಬೆಲ್ಲದಿಂದ ಮಾಡಿದ ಸಿಹಿ ಚಿಕ್ಕಿ. ಎಳ್ಳಿನಲ್ಲಿ ಹೆಚ್ಚಿನ ಕ್ಯಾಲ್ಸಿಯಂ ಇದ್ದರೂ, ಗರ್ಭಾವಸ್ಥೆಯ ಮೊದಲ ೧೨ ವಾರಗಳಲ್ಲಿ ಇದನ್ನು ಮಿತವಾಗಿರಿಸಬೇಕು.",
      hi: "तिल और गुड़ से बनी चिक्की। इसमें कैल्शियम प्रचुर मात्रा में होता है, लेकिन पहली तिमाही (<12 सप्ताह) में गर्भाशय संकुचन के डर से इसे सीमित रखने की सलाह दी जाती है।",
      ta: "எள் மற்றும் வெல்லத்தால் செய்யப்படும் மிட்டாய். கால்சியம் அதிகம் கொண்டது, எனினும் முதல் மூன்று மாதங்கள் தவிர்க்க அறிவுறுத்தப்படுகிறது.",
      te: "నువ్వులు మరియు బెల్లంతో చేసే చిక్కి. దీనిలో కాల్షియం ఎక్కువగా ఉన్నప్పటికీ, మొదటి త్రైమాసికంలో తక్కువగా తినడం మంచిది."
    },
    trimester: "2nd, 3rd",
    bestTime: "Evening Snack",
    benefits: {
      en: "Rich source of iron and plant-based calcium. Jaggery helps prevent anemia and boosts maternal energy.",
      kn: "ಕಬ್ಬಿಣ ಮತ್ತು ಸಸ್ಯಜನ್ಯ ಕ್ಯಾಲ್ಸಿಯಂನ ಉತ್ತಮ ಮೂಲವಾಗಿದೆ. ಬೆಲ್ಲವು ರಕ್ತಹೀನತೆ ತಡೆಯಲು ನೆರವಾಗುತ್ತದೆ.",
      hi: "आयरन और कैल्शियम का अच्छा स्रोत। गुड़ एनीमिया से बचाता है और ऊर्जा बढ़ाता है।",
      ta: "இரும்புச்சத்து மற்றும் கால்சியம் நிறைந்தது. வெல்லம் இரத்த சோகையைத் தடுத்து உடலுக்கு தெம்பு தரும்.",
      te: "ఐరన్ మరియు కాల్షియం అధికంగా లభిస్తాయి. బెల్లం రక్తహీనతను నివారించి శక్తిని ఇస్తుంది."
    },
    risks: {
      en: "Avoid in early pregnancy (First 12 Weeks). High sugar content; limit strictly in Gestational Diabetes.",
      kn: "ಮೊದಲ ೧೨ ವಾರಗಳಲ್ಲಿ ತಪ್ಪಿಸುವುದು ಸೂಕ್ತ. ಸಕ್ಕರೆ ಅಂಶ ಹೆಚ್ಚಿರುವುದರಿಂದ ಮಧುಮೇಹ ಇದ್ದವರು ಎಚ್ಚರದಿಂದಿರಬೇಕು.",
      hi: "गर्भावस्था के शुरुआती दिनों (पहले 12 सप्ताह) में बचें। मधुमेह होने पर इसका सेवन न करें।",
      ta: "ஆரம்பகால கர்ப்பத்தில் தவிர்க்கவும். நீரிழிவு உள்ளவர்கள் முற்றிலும் தவிர்க்க வேண்டும்.",
      te: "గర్భధారణ ప్రారంభంలో (మొదటి 12 వారాలు) తినకూడదు. మధుమేహం ఉన్నవారు దూరంగా ఉండాలి."
    },
    alternatives: "Groundnut Chikki, Almonds, Dates",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "boiled_egg",
    name: {
      en: "Boiled Egg (Fully Cooked)",
      kn: "ಬೇಯಿಸಿದ ಮೊಟ್ಟೆ",
      hi: "उबला हुआ अंडा",
      ta: "அவித்த முட்டை",
      te: "ఉడికించిన గుడ్డు"
    },
    category: "Eggs",
    calories: 78,
    protein: 6.3,
    carbohydrates: 0.6,
    fat: 5.3,
    fiber: 0,
    iron: 1.2,
    calcium: 28,
    folate: 22,
    vitaminA: 75,
    vitaminB6: 0.06,
    vitaminB12: 0.6,
    vitaminC: 0,
    vitaminD: 1.1,
    vitaminE: 0.5,
    vitaminK: 0.1,
    magnesium: 6,
    potassium: 69,
    zinc: 0.6,
    sodium: 62,
    sugar: 0.6,
    servingSize: "1 large egg (50g)",
    recommendedQuantity: "1-2 eggs daily",
    safetyLevel: "Safe",
    explanation: {
      en: "A pristine source of complete reference protein and choline, which is crucial for baby's brain development and genetic coding.",
      kn: "ಉತ್ತಮ ಪ್ರೋಟೀನ್ ಮತ್ತು ಕೋಲಿನ್ ಇರುವ ಆಹಾರ. ಇದು ಮಗುವಿನ ಮೆದುಳಿನ ಬೆಳವಣಿಗೆಗೆ ಮತ್ತು ಜೀನ್‌ಗಳ ಆರೋಗ್ಯಕ್ಕೆ ಬಹಳ ಮುಖ್ಯವಾಗಿದೆ.",
      hi: "उच्च गुणवत्ता वाले प्रोटीन और कोलीन का बेहतरीन स्रोत, जो शिशु के मस्तिष्क के विकास के लिए अत्यंत महत्वपूर्ण है।",
      ta: "உயர்தர புரதமும் கோலினும் நிறைந்தது, இது குழந்தையின் மூளை வளர்ச்சிக்கு மிகவும் இன்றியமையாதது.",
      te: "అత్యుత్తమ ప్రోటీన్ మరియు కోలిన్ లభించే ఆహారం. ఇది శిశువు మెదడు అభివృద్ధికి ఎంతో అవసరం."
    },
    trimester: "All",
    bestTime: "Breakfast",
    benefits: {
      en: "Choline (147mg) actively prevents neural tube defects. Highly digestible and helps build muscle tissue.",
      kn: "ಕೋಲಿನ್ ಮಗುವಿನ ನರಗಳ ವಿಕಾಸಕ್ಕೆ ನೆರವಾಗುತ್ತದೆ ಮತ್ತು ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗುವ ಪ್ರೋಟೀನ್ ನೀಡುತ್ತದೆ.",
      hi: "कोलीन शिशु के मस्तिष्क रोगों से रक्षा करता है। पचाने में आसान और मांसपेशियों के निर्माण में सहायक।",
      ta: "கோலின் தண்டுவட குறைபாடுகளை தடுக்கும். எளிதில் ஜீரணமாகக்கூடியது, தசைகளை வலுவாக்கும்.",
      te: "కోలిన్ నాడీ వ్యవస్థ లోపాలు రాకుండా కాపాడుతుంది. కండరాల నిర్మాణానికి తోడ్పడుతుంది."
    },
    risks: {
      en: "Never consume raw or runny yolks (half-boiled eggs) due to severe risk of Salmonella food poisoning.",
      kn: "ಸಾಲ್ಮೊನೆಲ್ಲಾ ಬ್ಯಾಕ್ಟೀರಿಯಾದ ವಿಷಾಹಾರ ತಡೆಯಲು ಅರೆ-ಬೇಯಿಸಿದ ಮೊಟ್ಟೆಗಳನ್ನು (ಹಾಫ್ ಬಾಯ್ಲ್) ತಿನ್ನಬೇಡಿ.",
      hi: "साल्मोनेला फूड पॉइजनिंग के खतरे के कारण कभी भी आधा उबला (Half-boiled) या कच्चा अंडा न खाएं।",
      ta: "சால்மோனெல்லா நச்சுத்தன்மையை தவிர்க்க அரைகுறையாக அவித்த முட்டைகளை சாப்பிட வேண்டாம்.",
      te: "సాల్మొనెల్లా బ్యాక్టీరియా ప్రమాదం నివారించడానికి హాఫ్ బాయిల్డ్ గుడ్లు అస్సలు తినకూడదు."
    },
    alternatives: "Paneer, Tofu, Sprouted Moong Dal",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: false,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "unripe_papaya",
    name: {
      en: "Unripe Papaya (Contains Latex)",
      kn: "ಹಸಿ ಪಪ್ಪಾಯಿ (ಹಾನಿಕಾರಕ)",
      hi: "कच्चा पपीता (हानिकारक)",
      ta: "பச்சை பப்பாளி (அபாயಕರமானது)",
      te: "పచ్చి బొప్పాయి (హానికరం)"
    },
    category: "Fruits",
    calories: 40,
    protein: 0.5,
    carbohydrates: 9.8,
    fat: 0.1,
    fiber: 1.8,
    iron: 0.3,
    calcium: 20,
    folate: 38,
    vitaminA: 0,
    vitaminB6: 0.03,
    vitaminB12: 0,
    vitaminC: 60,
    vitaminD: 0,
    vitaminE: 0.3,
    vitaminK: 2.6,
    magnesium: 10,
    potassium: 250,
    zinc: 0.1,
    sodium: 3,
    sugar: 6.0,
    servingSize: "None",
    recommendedQuantity: "Zero (Strictly Avoid)",
    safetyLevel: "Avoid",
    explanation: {
      en: "Unripe or semi-ripe papaya contains high concentrations of latex and papain, which can stimulate uterine contractions and trigger miscarriage or premature labor.",
      kn: "ಹಸಿ ಅಥವಾ ಅರೆ-ಬೆಂದ ಪಪ್ಪಾಯಿಯಲ್ಲಿ ಲ್ಯಾಟೆಕ್ಸ್ ಮತ್ತು ಪಪೈನ್ ಎಂಬ ರಾಸಾಯನಿಕಗಳಿದ್ದು, ಇವು ಗರ್ಭಾಶಯದ ಸಂಕುಚನವನ್ನು ಪ್ರಚೋದಿಸಿ ಗರ್ಭಪಾತಕ್ಕೆ ಕಾರಣವಾಗಬಹುದು.",
      hi: "कच्चे या अधपके पपीते में लेटेक्स और पपैन की अधिक मात्रा होती है, जो गर्भाशय के संकुचन को बढ़ाकर गर्भपात या समय पूर्व प्रसव (Premature labor) का कारण बन सकती है।",
      ta: "பச்சை பப்பாளியில் உள்ள லேடெக்ஸ் மற்றும் பப்பைன் கருப்பை சுருக்கத்தை தூண்டி, கருச்சிதைவு அல்லது முன்கூட்டிய பிரசவத்தை ஏற்படுத்தலாம்.",
      te: "పచ్చి బొప్పాయిలో ఉండే లేటెక్స్ మరియు పపైన్ అనే పదార్థాలు గర్భాశయ సంకోచాలను ప్రేరేపించి గర్భస్రావానికి దారితీయవచ్చు."
    },
    trimester: "All",
    bestTime: "None",
    benefits: {
      en: "None during pregnancy. Strictly avoided due to clinical contraindications.",
      kn: "ಗರ್ಭಾವಸ್ಥೆಯಲ್ಲಿ ಯಾವುದೇ ಪ್ರಯೋಜನಗಳಿಲ್ಲ. ಇದನ್ನು ಕಡ್ಡಾಯವಾಗಿ ತಪ್ಪಿಸಬೇಕು.",
      hi: "गर्भावस्था में कोई लाभ नहीं। इसे पूरी तरह वर्जित माना गया है।",
      ta: "கர்ப்பகாலத்தில் எந்த நன்மையும் இல்லை. முற்றிலும் தவிர்க்கப்பட வேண்டியது.",
      te: "గర్భధారణ సమయంలో ఎలాంటి ప్రయోజనాలు లేవు. ఖచ్చితంగా దూరంగా ఉంచాలి."
    },
    risks: {
      en: "Miscarriage, early uterine bleeding, and premature contractions. Extremely dangerous for the fetus.",
      kn: "ಗರ್ಭಪಾತ, ಗರ್ಭಾಶಯದ ರಕ್ತಸ್ರಾವ ಮತ್ತು ಅಕಾಲಿಕ ಹೆರಿಗೆ ನೋವು ಉಂಟಾಗುವ ತೀವ್ರ ಅಪಾಯವಿದೆ.",
      hi: "गर्भपात, आंतरिक रक्तस्राव और समय से पहले प्रसव पीड़ा का अत्यधिक जोखिम।",
      ta: "கருச்சிதைவு, இரத்தப்போக்கு மற்றும் முன்கூட்டிய பிரசவ வலி ஏற்படும் அபாயம் அதிகம்.",
      te: "గర్భస్రావం మరియు రక్తస్రావం జరిగే ప్రమాదం చాలా ఎక్కువ."
    },
    alternatives: "Fully ripe sweet papaya (skinless), Apple, Pomegranate",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "pineapple_fresh",
    name: {
      en: "Fresh Pineapple (Bromelain Rich)",
      kn: "ತಾಜಾ ಅನಾನಸ್ (ಮಿತವಾಗಿರಲಿ)",
      hi: "ताजा अनानास (सीमित मात्रा में)",
      ta: "அன்னாசிப்பழம் (அளவோடு)",
      te: "అనాసపండు (పరిమితంగా)"
    },
    category: "Fruits",
    calories: 50,
    protein: 0.5,
    carbohydrates: 13,
    fat: 0.1,
    fiber: 1.4,
    iron: 0.3,
    calcium: 13,
    folate: 18,
    vitaminA: 3,
    vitaminB6: 0.11,
    vitaminB12: 0,
    vitaminC: 48,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.7,
    magnesium: 12,
    potassium: 109,
    zinc: 0.1,
    sodium: 1,
    sugar: 10.0,
    servingSize: "1 small cup (80g)",
    recommendedQuantity: "Max 1 cup weekly (Safe in small doses)",
    safetyLevel: "Safe in Moderation",
    explanation: {
      en: "Pineapple contains bromelain, which can theoretically soften the cervix if consumed in massive quantities. Small, occasional amounts of fresh fruit are perfectly safe.",
      kn: "ಅನಾನಸ್‌ನಲ್ಲಿ ಬ್ರೋಮೆಲೈನ್ ಎಂಬ ಕಿಣ್ವವಿದ್ದು, ಇದನ್ನು ಅತಿಯಾಗಿ ಸೇವಿಸಿದರೆ ಗರ್ಭಾಶಯದ ಕಂಠವನ್ನು ಮೃದುಗೊಳಿಸಬಹುದು. ಆದರೆ ಮಿತವಾಗಿ ತಿನ್ನುವುದು ಸುರಕ್ಷಿತ.",
      hi: "अनानास में ब्रोमेलैन होता है, जो अत्यधिक मात्रा में खाने पर गर्भाशय ग्रीवा को ढीला कर सकता है। सीमित मात्रा में खाना पूरी तरह सुरक्षित है।",
      ta: "அன்னாசியில் உள்ள புரோமிலைன் அதிகளவில் உட்கொள்ளும்போது கருப்பை வாயை தளர்த்தலாம். வாரத்திற்கு ஒரு முறை சிறிதளவு சாப்பிடுவது பாதுகாப்பானது.",
      te: "అనాసపండులో బ్రోమెలైన్ ఉంటుంది, ఇది ఎక్కువ తింటే గర్భాశయ ద్వారం మెత్తబడేలా చేస్తుంది. పరిమితంగా తింటే ఏ ప్రమాదమూ లేదు."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "Superb Vitamin C content helps boost maternal immunity and enhances iron absorption from green leaves.",
      kn: "ಅತ್ಯುತ್ತಮ ವಿಟಮಿನ್ ಸಿ ಅಂಶವು ರೋಗನಿರೋಧಕ ಶಕ್ತಿಯನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ ಮತ್ತು ಕಬ್ಬಿಣದಂಶ ಹೀರಲು ನೆರವಾಗುತ್ತದೆ.",
      hi: "विटामिन सी का शानदार स्रोत जो रोग प्रतिरोधक क्षमता बढ़ाता है और आयरन के अवशोषण में मदद करता है।",
      ta: "வைட்டமின் சி நிறைந்துள்ளதால் நோய் எதிர்ப்பு சக்தி அதிகரிக்கும், இரும்புச்சத்து உறிஞ்சலையும் மேம்படுத்தும்.",
      te: "విటమిన్ సి అధికంగా ఉండి రోగనిరోధక శక్తిని పెంచుతుంది మరియు ఐరన్ గ్రహణకు తోడ్పడుతుంది."
    },
    risks: {
      en: "Can cause acid reflux or burning tongue if eaten in excess or on an empty stomach.",
      kn: "ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ ಅಥವಾ ಅತಿಯಾಗಿ ಸೇವಿಸಿದರೆ ಆಸಿಡ್ ರಿಫ್ಲಕ್ಸ್ ಮತ್ತು ನಾಲಿಗೆ ಉರಿಯನ್ನು ಉಂಟುಮಾಡಬಹುದು.",
      hi: "अधिक मात्रा में या खाली पेट खाने से एसिडिटी या जीभ में जलन हो सकती है।",
      ta: "வெறும் வயிற்றில் அல்லது அதிகளவில் சாப்பிட்டால் நெஞ்செரிச்சல் மற்றும் நாக்கு எரிச்சல் ஏற்படலாம்.",
      te: "ఖాళీ కడుపుతో తింటే గ్యాస్ట్రిక్ సమస్యలు లేదా నాలుక మంట రావచ్చు."
    },
    alternatives: "Apple, Sweet Lime (Mosambi), Orange",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "tender_coconut_water",
    name: {
      en: "Tender Coconut Water",
      kn: "ಎಳನೀರು",
      hi: "नारियल पानी (Coconut Water)",
      ta: "இளநீர்",
      te: "ఎలనీరు"
    },
    category: "Healthy Drinks",
    calories: 19,
    protein: 0.7,
    carbohydrates: 3.7,
    fat: 0.2,
    fiber: 1.1,
    iron: 0.3,
    calcium: 24,
    folate: 3,
    vitaminA: 0,
    vitaminB6: 0.03,
    vitaminB12: 0,
    vitaminC: 2.4,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    magnesium: 25,
    potassium: 250,
    zinc: 0.1,
    sodium: 105,
    sugar: 2.6,
    servingSize: "1 glass (250ml)",
    recommendedQuantity: "1 coconut daily",
    safetyLevel: "Safe",
    explanation: {
      en: "Nature's premier isotonic hydration fluid. Packed with magnesium and potassium to regulate maternal blood pressure and alleviate morning sickness.",
      kn: "ನೈಸರ್ಗಿಕ ಶಕ್ತಿಯ ಪಾನೀಯವಾಗಿದೆ. ರಕ್ತದೊತ್ತಡವನ್ನು ನಿಯಂತ್ರಿಸಲು ಮತ್ತು ಮುಂಜಾನೆಯ ಸುಸ್ತನ್ನು ನಿವಾರಿಸಲು ಮ್ಯಾಗ್ನೀಸಿಯಮ್ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಮ್ ಒದಗಿಸುತ್ತದೆ.",
      hi: "प्रकृति का सबसे बेहतरीन हाइड्रेशन पेय। रक्तचाप को नियंत्रित करने और उल्टी से राहत दिलाने के लिए पोटैशियम और मैग्नीशियम से भरपूर।",
      ta: "இயற்கையான நீரேற்ற பானம். இரத்த அழுத்தத்தை சீராக்கவும் காலையில் ஏற்படும் களைப்பை போக்கவும் பொட்டாசியம் மற்றும் மெக்னீசியம் நிறைந்தது.",
      te: "ప్రకృతి ప్రసాదించిన అద్భుతమైన ద్రవాహారం. పొటాషియం మరియు మెగ్నీషియం ఉండి గర్భిణుల రక్తపోటును అదుపులో ఉంచుతుంది."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "Prevents dehydration and muscle cramps; naturally cleanses the urinary tract to prevent infections.",
      kn: "ನಿರ್ಜಲೀಕರಣ ಮತ್ತು ಸ್ನಾಯುಗಳ ಸೆಳೆತವನ್ನು ತಡೆಯುತ್ತದೆ; ಮೂತ್ರನಾಳದ ಸೋಂಕನ್ನು ನಿವಾರಿಸಲು ಸಹಕಾರಿ.",
      hi: "डीहाइड्रेशन और मांसपेशियों के खिंचाव को रोकता है; मूत्र मार्ग के संक्रमण (UTI) से बचाता है।",
      ta: "உடல் வறட்சி மற்றும் தசைப்பிடிப்புகளை தடுக்கும்; சிறுநீர் பாதை தொற்றுகளை குணமாக்கும்.",
      te: "శరీర నిర్జలీకరణం మరియు కండరాల నొప్పులను నివారిస్తుంది; మూత్రపిండాల ఇన్ఫెక్షన్లను తగ్గిస్తుంది."
    },
    risks: {
      en: "Extremely safe. Drink immediately after cracking to prevent any bacterial contamination.",
      kn: "ಅತ್ಯಂತ ಸುರಕ್ಷಿತ ಪಾನೀಯ. ಬ್ಯಾಕ್ಟೀರಿಯಾ ಸೋಂಕು ತಡೆಯಲು ಕತ್ತರಿಸಿದ ತಕ್ಷಣ ಕುಡಿಯಿರಿ.",
      hi: "अत्यंत सुरक्षित। काटने के तुरंत बाद पिएं ताकि कोई कीटाणु संक्रमण न हो।",
      ta: "மிகவும் பாதுகாப்பானது. வெட்டிய உடனே குடிக்கவும்.",
      te: "చాలా సురక్షితమైనది. కాయ కొట్టిన వెంటనే తాగాలి."
    },
    alternatives: "Butter milk, Sabja water, Fresh lime juice",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "nongu_palm_fruit",
    name: {
      en: "Nongu Palm Fruit (Ice Apple)",
      kn: "ತಾಟಿನುಂಗು",
      hi: "ताड़गोला (नोंगू)",
      ta: "நுங்கு",
      te: "తాటి ముంజలు"
    },
    category: "Fruits",
    calories: 43,
    protein: 0.8,
    carbohydrates: 10.2,
    fat: 0.1,
    fiber: 1.2,
    iron: 0.4,
    calcium: 27,
    folate: 0,
    vitaminA: 0,
    vitaminB6: 0.01,
    vitaminB12: 0,
    vitaminC: 5,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    magnesium: 12,
    potassium: 145,
    zinc: 0.1,
    sodium: 10,
    sugar: 8.5,
    servingSize: "2-3 pieces (100g)",
    recommendedQuantity: "2-3 pieces during summer",
    safetyLevel: "Safe",
    explanation: {
      en: "A refreshing, translucent palm fruit native to coastal South India. Excellent coolant that relieves stomach irritation and morning sickness.",
      kn: "ದಕ್ಷಿಣ ಭಾರತದ ಕರಾವಳಿಯ ನೈಸರ್ಗಿಕ ತಂಪಾದ ಹಣ್ಣು. ಇದು ಹೊಟ್ಟೆಯುರಿ ಮತ್ತು ಮುಂಜಾನೆಯ ವಾಕರಿಕೆಯನ್ನು ಹೋಗಲಾಡಿಸುತ್ತದೆ.",
      hi: "तटीय दक्षिण भारत का एक ताज़ा फल। यह पेट की जलन और उल्टी की समस्या को दूर करने वाला एक बेहतरीन प्राकृतिक शीतलक (Coolant) है।",
      ta: "தென்னிந்தியாவின் பாரம்பரிய நுங்கு பழம். உடலை குளிர்வித்து வயிற்று எரிச்சல் மற்றும் குமட்டலை போக்கும் சிறந்த பழம்.",
      te: "తీర ప్రాంతాలలో లభించే అద్భుతమైన తాటి ముంజలు. ఇది శరీర ఉష్ణోగ్రతను తగ్గించి, వికారాన్ని అదుపులో ఉంచుతుంది."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "Natural coolant; helps maintain body temperature and treats digestive issues during pregnancy.",
      kn: "ನೈಸರ್ಗಿಕ ತಂಪುಕಾರಿ; ಗರ್ಭಾವಸ್ಥೆಯಲ್ಲಿ ದೇಹದ ಉಷ್ಣತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಜೀರ್ಣಕ್ರಿಯೆಗೆ ನೆರವಾಗುತ್ತದೆ.",
      hi: "प्राकृतिक शीतलक; शरीर के तापमान को बनाए रखता है और पाचन संबंधी समस्याओं को दूर करता है।",
      ta: "இயற்கை குளிர்ச்சி தரும்; கர்ப்பகால உடல் சூட்டை தணித்து செரிமானத்தை சீராக்கும்.",
      te: "శరీరానికి చలువ చేస్తుంది; గర్భిణుల జీర్ణ సమస్యలను నివారిస్తుంది."
    },
    risks: {
      en: "Consume fresh palm fruit immediately. Do not buy pre-peeled fruit exposed to dust.",
      kn: "ತಾಜಾ ತಾಟಿನುಂಗನ್ನು ತಕ್ಷಣ ಸೇವಿಸಿ. ಸುಲಿದು ತೆರೆದಿಟ್ಟ ಹಣ್ಣುಗಳನ್ನು ಕೊಳ್ಳಬೇಡಿ.",
      hi: "हमेशा ताजा फल ही खाएं। पहले से छिले हुए और धूल के संपर्क में आए फलों से बचें।",
      ta: "புதிய நுங்கை உடனே சாப்பிடவும். தோல் நீக்கி நீண்ட நேரம் வைத்திருப்பதை தவிர்க்கவும்.",
      te: "తాజా ముంజలను వెంటనే తినాలి. ఎక్కువ సమయం నిల్వ ఉంచినవి తినకూడదు."
    },
    alternatives: "Watermelon, Tender Coconut, Muskmelon",
    states: ["Tamil Nadu", "Puducherry", "Andhra Pradesh", "Telangana", "Karnataka"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "nendran_banana",
    name: {
      en: "Nendran Banana (Steamed)",
      kn: "ನೆಂದ್ರನ್ ಬಾಳೆಹಣ್ಣು (ಬೇಯಿಸಿದ್ದು)",
      hi: "नेन्द्रन केला (भाप में पका)",
      ta: "நேந்திரம் பழம் (அவித்தது)",
      te: "నేంద్రన్ అరటిపండు (ఉడికించినది)"
    },
    category: "Fruits",
    calories: 116,
    protein: 1.2,
    carbohydrates: 31,
    fat: 0.2,
    fiber: 3.0,
    iron: 0.6,
    calcium: 15,
    folate: 22,
    vitaminA: 40,
    vitaminB6: 0.36,
    vitaminB12: 0,
    vitaminC: 15,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 0.8,
    magnesium: 35,
    potassium: 485,
    zinc: 0.2,
    sodium: 4,
    sugar: 16.0,
    servingSize: "1 banana (100g)",
    recommendedQuantity: "1 daily for breakfast/snack",
    safetyLevel: "Safe",
    explanation: {
      en: "Steamed Nendran banana is a traditional Kerala pregnancy superfood. It is rich in potassium and Vitamin B6, which dramatically helps reduce morning sickness.",
      kn: "ಬೇಯಿಸಿದ ನೆಂದ್ರನ್ ಬಾಳೆಹಣ್ಣು ಗರ್ಭಿಣಿಯರಿಗೆ ಅತ್ಯುತ್ತಮ ಆಹಾರವಾಗಿದೆ. ಇದರಲ್ಲಿರುವ ಪೊಟ್ಯಾಸಿಯಮ್ ಮತ್ತು ವಿಟಮಿನ್ ಬಿ೬ ಮುಂಜಾನೆಯ ಸುಸ್ತನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.",
      hi: "भाप में पका नेन्द्रन केला केरल का पारंपरिक गर्भावस्था सुपरफूड है। यह पोटैशियम और विटामिन बी6 से भरपूर है, जो उल्टी की समस्या को दूर करता है।",
      ta: "அவித்த நேந்திரம் பழம் கர்ப்பிணிகளுக்கான சிறந்த பாரம்பரிய உணவு. இதிலுள்ள பொட்டாசியமும் வைட்டமின் B6-ம் குமட்டலை போக்கும்.",
      te: "ఉడికించిన నేంద్రన్ అరటిపండు గర్భిణులకు ఎంతో మేలు చేస్తుంది. దీనిలోని పొటాషియం మరియు విಟమిన్ బి6 వికారాన్ని తగ్గిస్తాయి."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "Outstanding Vitamin B6 and potassium levels help manage nerves and muscular strength.",
      kn: "ಅತ್ಯುತ್ತಮ ವಿಟಮಿನ್ ಬಿ೬ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಮ್ ಮಟ್ಟಗಳು ನರಗಳ ಮತ್ತು ಸ್ನಾಯುಗಳ ಬಲವನ್ನು ಕಾಪಾಡಲು ನೆರವಾಗುತ್ತವೆ.",
      hi: "शानदार विटामिन बी6 और पोटैशियम जो मांसपेशियों की ताकत और तंत्रिकाओं को स्वस्थ रखते हैं।",
      ta: "வைட்டமின் B6 மற்றும் பொட்டாசியம் நிறைந்துள்ளதால் தசை வலிமைக்கும் நரம்பு மண்டலத்திற்கும் நல்லது.",
      te: "అద్భుతమైన విటమిన్ బి6 మరియు పొటాషియం నరాల బలాన్ని, కండరాల శక్తిని పెంచుతాయి."
    },
    risks: {
      en: "Eat steamed to increase starch digestibility. High natural sugars, so limit in GDM.",
      kn: "ಸುಲಭವಾಗಿ ಜೀರ್ಣವಾಗಲು ಹಬೆಯಲ್ಲಿ ಬೇಯಿಸಿ ತಿನ್ನಿ. ಸಕ್ಕರೆ ಪ್ರಮಾಣ ಹೆಚ್ಚಿರುವುದರಿಂದ ಮಧುಮೇಹ ಇದ್ದರೆ ನಿಯಂತ್ರಿಸಿ.",
      hi: "आसानी से पचाने के लिए इसे भाप में पकाकर खाएं। प्राकृतिक शर्करा अधिक होने के कारण मधुमेह रोगी कम खाएं।",
      ta: "எளிதில் செரிமானமாக அவித்து சாப்பிடவும். சர்க்கரை அதிகம் உள்ளதால் நீரிழிவு நோயாளிகள் கவனமாக இருக்கவும்.",
      te: "సులಭంగా జీర్ణమవడానికి ఉడికించి తినాలి. చక్కెర ఎక్కువ కాబట్టి మధుమేహులు పరిమితంగా తినాలి."
    },
    alternatives: "Regular Banana, Robusta, Apple",
    states: ["Kerala", "Tamil Nadu", "Karnataka"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1566393028639-d108a42c46a7?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "soaked_almonds",
    name: {
      en: "Soaked Almonds (Skins Removed)",
      kn: "ನೆನೆಸಿದ ಬಾದಾಮಿ (ಸಿಪ್ಪೆ ಸುಲಿದಿದ್ದು)",
      hi: "भीगे बादाम (बिना छिलके)",
      ta: "ஊறவைத்த தோல் நீக்கிய பாதாம்",
      te: "నానబెట్టిన పొట్టుతీసిన బాదం"
    },
    category: "Nuts",
    calories: 120,
    protein: 4.5,
    carbohydrates: 4.2,
    fat: 10.5,
    fiber: 2.5,
    iron: 0.8,
    calcium: 55,
    folate: 10,
    vitaminA: 0,
    vitaminB6: 0.03,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 5.2,
    vitaminK: 0.1,
    magnesium: 54,
    potassium: 140,
    zinc: 0.6,
    sodium: 2,
    sugar: 0.9,
    servingSize: "4-5 almonds soaked",
    recommendedQuantity: "4-5 almonds daily morning",
    safetyLevel: "Safe",
    explanation: {
      en: "Almonds soaked overnight and peeled. Removing the skin eliminates tannins, improving nutrient absorption. A superb source of Vitamin E and healthy lipids.",
      kn: "ರಾತ್ರಿ ಇಡೀ ನೆನೆಸಿ ಸಿಪ್ಪೆ ಸುಲಿದ ಬಾದಾಮಿ. ಸಿಪ್ಪೆ ತೆಗೆಯುವುದರಿಂದ ಪೋಷಕಾಂಶಗಳ ಹೀರಿಕೊಳ್ಳುವಿಕೆ ಹೆಚ್ಚಾಗುತ್ತದೆ. ಇದು ವಿಟಮಿನ್ ಇ ನ ಉತ್ತಮ ಮೂಲವಾಗಿದೆ.",
      hi: "रातभर भीगे और छिले हुए बादाम। छिलका हटाने से पोषक तत्वों का अवशोषण सुधरता है। विटामिन ई और स्वस्थ वसा का बेहतरीन स्रोत।",
      ta: "இரவு முழுவதும் ஊறவைத்து தோல் நீக்கப்பட்ட பாதாம். தோலை நீக்குவதால் சத்துக்கள் முழுமையாக உடலுக்கு கிடைக்கும். வைட்டமின் ஈ நிறைந்தது.",
      te: "రాత్రంతా నానబెట్టి పొట్టుతీసిన బాదంపప్పులు. పొట్టు తీయడం వల్ల పోషకాలు బాగా అందుతాయి. విటమిన్ ఇ ఎక్కువగా లభిస్తుంది."
    },
    trimester: "All",
    bestTime: "Morning Snack",
    benefits: {
      en: "High Vitamin E (5.2mg) supports fetal skin and cell wall integrity; magnesium regulates muscle relaxation.",
      kn: "ವಿಟಮಿನ್ ಇ ಮಗುವಿನ ಚರ್ಮದ ಬೆಳವಣಿಗೆಗೆ ಸಹಕಾರಿ; ಮ್ಯಾಗ್ನೀಸಿಯಮ್ ಸ್ನಾಯುಗಳ ಸೆಳೆತವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.",
      hi: "विटामिन ई भ्रूण की त्वचा के विकास में मदद करता है। मैग्नीशियम मांसपेशियों को आराम देता है।",
      ta: "வைட்டமின் ஈ குழந்தையின் சரும வளர்ச்சிக்கு நல்லது. மெக்னீசியம் தசைப்பிடிப்புகளை தளர்த்தும்.",
      te: "విటమిన్ ఇ శిశువు చర్మ ఆరోగ్యానికి మంచిది. మెగ్నీషియం కండరాల నొప్పులను తగ్గిస్తుంది."
    },
    risks: {
      en: "Always peel to prevent throat irritation. Do not consume raw almonds in excess.",
      kn: "ಸಿಪ್ಪೆ ಸುಲಿದು ತಿನ್ನಿ. ಹಸಿ ಬಾದಾಮಿಯನ್ನು ಅತಿಯಾಗಿ ಸೇವಿಸಬೇಡಿ.",
      hi: "हमेशा छिलका उतारकर ही खाएं। कच्चे सूखे बादाम अधिक मात्रा में न खाएं।",
      ta: "தொண்டை எரிச்சலை தவிர்க்க தோலை நீக்கவும். பச்சையாக பாதாம் பருப்பை அதிகம் சாப்பிட வேண்டாம்.",
      te: "గొంతు నొప్పి రాకుండా పొట్టుతీసి తినాలి. పచ్చి బాదం పప్పులను ఎక్కువ తినకూడదు."
    },
    alternatives: "Soaked Walnuts, Cashews, Raisins",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1508888633167-93721309bcb0?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "dates_khajur",
    name: {
      en: "Premium Dates (Khajur)",
      kn: "ಖರ್ಜೂರ",
      hi: "खजूर (Dates)",
      ta: "பேரீச்சம்பழம்",
      te: "ఖర్జూరం"
    },
    category: "Dry Fruits",
    calories: 140,
    protein: 1.1,
    carbohydrates: 37,
    fat: 0.1,
    fiber: 4.0,
    iron: 1.5,
    calcium: 32,
    folate: 9,
    vitaminA: 2,
    vitaminB6: 0.12,
    vitaminB12: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0.1,
    vitaminK: 1.4,
    magnesium: 24,
    potassium: 325,
    zinc: 0.2,
    sodium: 1,
    sugar: 32.0,
    servingSize: "2 pieces (50g)",
    recommendedQuantity: "2 pieces daily (especially in Trimester 3)",
    safetyLevel: "Safe",
    explanation: {
      en: "Dates are nature's candy, loaded with iron, potassium, and fiber. Clinical studies show eating dates in late pregnancy can support cervical dilation and ease labor.",
      kn: "ಖರ್ಜೂರವು ನೈಸರ್ಗಿಕ ಸಿಹಿಯಾಗಿದ್ದು ಕಬ್ಬಿಣ, ಪೊಟ್ಯಾಸಿಯಮ್ ಮತ್ತು ನಾರಿನಂಶವನ್ನು ಹೊಂದಿದೆ. ಗರ್ಭಾವಸ್ಥೆಯ ಕೊನೆಯ ಹಂತದಲ್ಲಿ ಇದನ್ನು ತಿನ್ನುವುದರಿಂದ ಹೆರಿಗೆ ಸುಲಭವಾಗುತ್ತದೆ.",
      hi: "खजूर आयरन, पोटैशियम और फाइबर से भरपूर होते हैं। अंतिम तिमाही में खजूर खाने से प्रसव (Labor) आसान होने में मदद मिलती है।",
      ta: "பேரீச்சம்பழம் இரும்பு, பொட்டாசியம் மற்றும் நார்சத்து நிறைந்தது. கர்ப்பத்தின் கடைசி வாரங்களில் சாப்பிடுவது பிரசவத்தை எளிதாக்கும்.",
      te: "ఖర్జూరంలో ఐరన్, పొటాషియం మరియు ఫైబర్ పుష్కలంగా ఉంటాయి. చివరి నెలల్లో ఖర్జూరం తింటే ప్రసవం సులభమవుతుందని పరిశోధనలు చెబుతున్నాయి."
    },
    trimester: "All",
    bestTime: "Evening Snack",
    benefits: {
      en: "High fiber treats pregnancy constipation. Potassium regulates fluid balance. Encourages natural cervical dilation.",
      kn: "ಹೆಚ್ಚಿನ ನಾರಿನಂಶವು ಮಲಬದ್ಧತೆಯನ್ನು ನಿವಾರಿಸುತ್ತದೆ. ಪೊಟ್ಯಾಸಿಯಮ್ ದೇಹದ ದ್ರವ ಸಮತೋಲನವನ್ನು ಕಾಪಾಡುತ್ತದೆ.",
      hi: "कब्ज से राहत दिलाता है। पोटैशियम शरीर में तरलता बनाए रखता है। प्रसव के समय को सुगम बनाता है।",
      ta: "நார்ச்சத்து மலச்சிக்கலை தீர்க்கும். பொட்டாசியம் திரவ சமநிலையை பேணும். பிரசவ வலியை எளிதாக்கும்.",
      te: "మలబద్ధకం తగ్గిస్తుంది. శరీరంలో నీటి శాతాన్ని సమతుల్యం చేస్తుంది. సుఖ ప్రసవానికి సహాయపడుతుంది."
    },
    risks: {
      en: "Extremely high sugar; must be completely avoided or restricted in Gestational Diabetes.",
      kn: "ಅತಿ ಹೆಚ್ಚು ಸಕ್ಕರೆ ಇರುವುದರಿಂದ ಗರ್ಭಾವಸ್ಥೆಯ ಮಧುಮೇಹ ಇದ್ದವರು ಇದನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ತಪ್ಪಿಸಬೇಕು.",
      hi: "शर्करा की बहुत अधिक मात्रा; गर्भकालीन मधुमेह (GDM) के रोगियों को इससे बचना चाहिए।",
      ta: "அதிக சர்க்கரை கொண்டது; கர்ப்பகால நீரிழிவு உள்ளவர்கள் முற்றிலும் தவிர்க்க வேண்டும்.",
      te: "చక్కెర చాలా ఎక్కువ; గర్భధారణ మధుమేహం ఉంటే దీనిని తినకూడదు."
    },
    alternatives: "Prunes, Dried Figs, Raisins",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&q=80&w=300"
  },
  {
    id: "cooked_spinach_palak",
    name: {
      en: "Cooked Spinach (Palak)",
      kn: "ಬೇಯಿಸಿದ ಪಾಲಕ್ ಸೊಪ್ಪು",
      hi: "पका हुआ पालक (पालक भाजी)",
      ta: "சமைத்த பசலைக்கீரை (பாலக்)",
      te: "ఉడికించిన పాలకూర (పాలక్)"
    },
    category: "Leafy Greens",
    calories: 40,
    protein: 3.5,
    carbohydrates: 6.8,
    fat: 0.5,
    fiber: 3.2,
    iron: 4.0,
    calcium: 136,
    folate: 146,
    vitaminA: 460,
    vitaminB6: 0.18,
    vitaminB12: 0,
    vitaminC: 18,
    vitaminD: 0,
    vitaminE: 1.5,
    vitaminK: 320,
    magnesium: 68,
    potassium: 370,
    zinc: 0.6,
    sodium: 120,
    sugar: 0.4,
    servingSize: "1 cup (150g)",
    recommendedQuantity: "1 cup 2-3 times weekly",
    safetyLevel: "Safe",
    explanation: {
      en: "Cooked spinach is exceptionally dense in dietary folate and iron. Crucial for early embryonic spinal development and blood hemoglobin production.",
      kn: "ಬೇಯಿಸಿದ ಪಾಲಕ್ ಸೊಪ್ಪಿನಲ್ಲಿ ಫೋಲೇಟ್ ಮತ್ತು ಕಬ್ಬಿಣದಂಶ ಹೇರಳವಾಗಿದೆ. ಮಗುವಿನ ಬೆನ್ನುಹುರಿಯ ಬೆಳವಣಿಗೆಗೆ ಮತ್ತು ರಕ್ತದ ಹಿಮೋಗ್ಲೋಬಿನ್ ಹೆಚ್ಚಿಸಲು ಇದು ಮುಖ್ಯವಾಗಿದೆ.",
      hi: "पका हुआ पालक फोलेट और आयरन से भरपूर होता है। शिशु के रीढ़ की हड्डी के विकास और हीमोग्लोबिन बढ़ाने के लिए आवश्यक।",
      ta: "சமைத்த பசலைக்கீரையில் ஃபோலேட்டும் இரும்பும் மிக அதிகம். குழந்தையின் தண்டுவட வளர்ச்சிக்கும் இரத்த சோகையை தடுக்கவும் உதவும்.",
      te: "ఉడికించిన పాలకూరలో ఫోలేట్, ఐరన్ సమృద్ధిగా లభిస్తాయి. పిండం వెన్నెముక అభివృద్ధికి మరియు హిమోగ్లోబిన్ వృద్ధికి సహాయపడుతుంది."
    },
    trimester: "All",
    bestTime: "Lunch",
    benefits: {
      en: "Extremely high folate (146mcg) prevents spinal birth defects. Iron (4.0mg) prevents anemia.",
      kn: "ಹೆಚ್ಚಿನ ಫೋಲೇಟ್ ಬೆನ್ನುಹುರಿಯ ದೋಷಗಳನ್ನು ತಡೆಯುತ್ತದೆ. ಕಬ್ಬಿಣದಂಶವು ರಕ್ತಹೀನತೆಯನ್ನು ತಡೆಯುತ್ತದೆ.",
      hi: "उच्च फोलेट (146mcg) जन्म दोषों से रक्षा करता है। आयरन (4.0mg) रक्त की कमी को दूर करता है।",
      ta: "அதிக ஃபோலேட் (146mcg) பிறப்பு குறைபாடுகளை தடுக்கும். இரும்புச்சத்து (4.0mg) இரத்த சோகையை போக்கும்.",
      te: "అధిక ఫోలేట్ (146mcg) వెన్నెముక లోపాలను నివారిస్తుంది. ఐరన్ (4.0mg) రక్తహీనతను రానివ్వదు."
    },
    risks: {
      en: "Never consume raw spinach due to presence of oxalates and risk of soil-borne bacterial infections. Cook thoroughly.",
      kn: "ಕಚ್ಚಾ ಸೊಪ್ಪನ್ನು ತಿನ್ನಬೇಡಿ. ಆಕ್ಸಲೇಟ್ ಅಂಶ ಇರುವುದರಿಂದ ಸೊಪ್ಪನ್ನು ಯಾವಾಗಲೂ ಚೆನ್ನಾಗಿ ಬೇಯಿಸಿ ಸವಿಯಿರಿ.",
      hi: "ऑक्सालेट और बैक्टीरिया के खतरे के कारण कभी भी कच्चा पालक न खाएं। हमेशा अच्छी तरह पकाकर खाएं।",
      ta: "பச்சையாக கீரையை சாப்பிட வேண்டாம், இதிலுள்ள ஆக்சலேட்டுகள் சத்துக்களை உடல் உறிஞ்ச விடாது. நன்றாக சமைத்து உண்ணவும்.",
      te: "పచ్చి పాలకూర తినకూడదు, ఆక్సలేట్ల వల్ల కిడ్నీ స్టోన్స్ రావచ్చు. ఎప్పుడూ బాగా ఉడికించి తినాలి."
    },
    alternatives: "Moringa soup, Amaranth leaves, Methi (Fenugreek)",
    states: ["Karnataka", "Tamil Nadu", "Kerala", "Andhra Pradesh", "Telangana", "Puducherry"],
    isVegetarian: true,
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=300"
  }
];
